Hide OldSBMenu and PetOverlay while being in the rift
NotEnoughUpdates/NotEnoughUpdates pull request #1008
Opened 2024-01-21 13:32 UTC by jani270

2024-01-21 19:35 UTC, nea89o requested changes

2024-01-21 19:35 UTC, nea89o commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PetInfoOverlay.java
> +			SBInfo.getInstance().getLocation() != null && SBInfo.getInstance().getLocation().equals("rift")) {
Please place clarifying parenthesis around this. Alternatively: 

```suggestion
			Objects.equals(SBInfo.getInstance().getLocation(), "rift")) {
```

2024-01-21 19:35 UTC, nea89o commented on src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/OldSkyBlockMenu.kt
> +        if (SBInfo.getInstance().getLocation() != null && SBInfo.getInstance().getLocation() == "rift") return
Please use `.equals` instead of `==`.

2024-01-21 20:07 UTC, nea89o approved these changes

2024-01-23 19:16 UTC, Lulonaut approved these changes

2024-01-23 19:16 UTC, merged