Added Recipe Search Overlay
NotEnoughUpdates/NotEnoughUpdates pull request #1044
Opened 2024-03-11 20:56 UTC by Conutik

Added recipe search overlay which uses the same way ah and bz search overlays are made.

Known bugs that I couldn't fix:
- [ ] Ghost shadow appearing in different pages other than crafting menu without the pickaxe.
- [ ] Shift clicking an item crashes the game

(Third time's the charm)

2024-03-11 21:04 UTC, jani270 commented on build.gradle.kts
> +	/*
What happend here lol

2024-03-11 21:07 UTC, jani270 requested changes
Please format your files with the Intellij built in formatter

2024-03-11 21:27 UTC, Conutik commented on build.gradle.kts
> +	/*
I think I pressed tab by accident D:

2024-03-11 22:29 UTC, nea89o commented
Hey, it looks like you accidentally build your PR based on https://github.com/Moulberry/NotEnoughUpdates instead of https://github.com/NotEnoughUpdates/NotEnoughUpdates. You might need to rebase some of your code on the latest commit from here.

2024-03-12 06:44 UTC, Conutik commented
Fixed all comments above

2024-03-12 10:42 UTC, jani270 commented
> Fixed all comments above

Unfortunatly that is still wrong, see merge conflicts. Your branch is still based on Moulberry/NEU instead of NEU/NEU. Which makes this impossible to merge.

2024-03-12 10:44 UTC, jani270 requested changes

2024-03-12 10:44 UTC, jani270 commented on src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
> +	public BazaarTweaks recipeTweaks = new BazaarTweaks();
BazaarTweaks

2024-03-12 10:44 UTC, jani270 commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/RecipeTweaks.java
> +		desc = "Make pressing ESCAPE close the search GUI without opening up the Bazaar again\n" +
Bazaar

2024-03-12 10:44 UTC, jani270 commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/RecipeSearchOverlay.java
> +			desc.retainAll(bazaarItems);
Bazaar

2024-03-12 10:44 UTC, jani270 commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/RecipeSearchOverlay.java
> +							new GuiScreenElementWrapper(new NEUConfigEditor(NotEnoughUpdates.INSTANCE.config, "Bazaar Tweaks"));
Bazaar Tweaks

2024-03-12 11:50 UTC, closed without merging