Added an command to change repo url and commits url
NotEnoughUpdates/NotEnoughUpdates pull request #109
Opened 2022-04-01 13:49 UTC by NopoTheGamer

There is a chance i forgot to make a pr

2022-04-01 13:51 UTC, Lulonaut submitted a review, later dismissed

2022-04-01 14:31 UTC, Lulonaut submitted a review, later dismissed

2022-04-07 10:16 UTC, DeDiamondPro submitted a review, later dismissed

2022-04-10 20:11 UTC, romangraef requested changes
Since repo download url and commit url always get changed in tandem i feel like a `/neurepomode setrepoupstream <githubuser> <reponame> <branch>` with potentially 2 of these arguments being optional (if only one arg is supplied use neu/neu-repo with that branch) would be a lot more useful and a lot less confusing(this is currently terrible UX). we are already locking ourselves to using only github by using the github api (which isn't the same accross git hosts) so i dont see a reason not to.

2022-04-10 20:12 UTC, romangraef commented
Also not entirely sure, but it might be good to run /neuresetrepo when changing the urls (and also maybe consolidate /neuresetrepo in this command somehow)

2022-04-11 03:51 UTC, NopoTheGamer commented
> Also not entirely sure, but it might be good to run /neuresetrepo when changing the urls (and also maybe consolidate /neuresetrepo in this command somehow)

I don't really see a need to run neuresetrepo automatically. The person running the command should know if they need to reset repo or not

also the commits should be different so neu should redownload the repo anyway?

2022-04-11 06:02 UTC, romangraef approved these changes

2022-04-11 11:55 UTC, Lulonaut approved these changes

2022-04-12 16:23 UTC, DeDiamondPro approved these changes

2022-04-12 16:23 UTC, merged