Add /neucheck command & check for enchant parsers
NotEnoughUpdates/NotEnoughUpdates pull request #1166
Opened 2024-05-12 00:01 UTC by Madeleaan

Adds an **/neucheck** command boilerplate so we can notify user about incompatibilities with other mods. It mainly servers to reduce headaches in neu-support (we need jani to keep his sanity).
Also already implements **/neucheck neuec** that returns which mods are loaded and how to disable the enchant parsing in them.

This can be obviously modified to check for the actual setting if parsing is enabled & set it to the correct value.
But i am bad at kotlin reflections and I will have close to no free time next week so just wanted to push this out...

![obrazek](https://github.com/NotEnoughUpdates/NotEnoughUpdates/assets/70163122/7fbe1467-367a-4068-bef2-a8099835cefb)
![obrazek](https://github.com/NotEnoughUpdates/NotEnoughUpdates/assets/70163122/0f58f7b1-ddf3-4f50-95bb-d5a103268aa0)

2024-05-14 05:19 UTC, NopoTheGamer requested changes

2024-05-14 05:19 UTC, NopoTheGamer commented on src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/checks/EnchantsCheck.kt
> +    private fun isModInstalled(clazz: String): Boolean {
Why are we doing this instead of Loader.isModLoaded()

2024-05-14 05:20 UTC, NopoTheGamer requested changes

2024-05-14 05:20 UTC, NopoTheGamer commented on src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/checks/EnchantsCheck.kt
> +    private val dsmCheck = "me.Danker.DankersSkyblockMod"
also sbe has enchant colours

2024-05-14 05:20 UTC, NopoTheGamer commented on src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/checks/EnchantsCheck.kt
> +        if(isModInstalled(sbaCheck)) messages.add(modMessage(sbaMsg, sbaHelp, "/sba"))
use intellij auto formatting

2024-05-28 23:25 UTC, NopoTheGamer approved these changes

2024-05-31 11:52 UTC, Lulonaut approved these changes

2024-05-31 12:16 UTC, merged