Fix slot binding in chest or non-player GUIs
NotEnoughUpdates/NotEnoughUpdates pull request #1189
Opened 2024-05-29 19:09 UTC by IndigoPolecat

Fix a desync between the event slot number and the gui slot number.

2024-05-29 19:12 UTC, IndigoPolecat commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/SlotLocking.java
> +			// I don't know of a way to detect non-player inventories but it should to apply here and L505
it was a mistake from another bug I tried to fix but was unable to, I removed the line I was referring to already and I added a commit that adjusted the comment a minute ago

2024-05-29 23:14 UTC, NopoTheGamer commented
Does this fix https://github.com/NotEnoughUpdates/NotEnoughUpdates/issues/519 ?

2024-05-29 23:30 UTC, IndigoPolecat commented
> Does this fix #519 ?

I didn't realise there was an issue open but yes it does.
I also just added a commit to remove a very dumb assumption I had made which means it will now work in any situation, regardless of if the total inventory has less than 45 slots (like a furnace).

2024-05-30 11:46 UTC, NopoTheGamer requested changes
If you shift click from hotbar it will just go into the chest and then the link will be broken once you exit the chest. Slot binding just full doesn't work either side in the furnace, did notice it works perfectly in the dropper

2024-05-30 15:17 UTC, IndigoPolecat commented
> If you shift click from hotbar it will just go into the chest and then the link will be broken once you exit the chest. Slot binding just full doesn't work either side in the furnace, did notice it works perfectly in the dropper

That's odd, I tested in a furnace but I'll double check, I think the other issue was pre existing but I'll look into it as well

2024-05-30 15:43 UTC, IndigoPolecat commented
> > If you shift click from hotbar it will just go into the chest and then the link will be broken once you exit the chest. Slot binding just full doesn't work either side in the furnace, did notice it works perfectly in the dropper
> 
> That's odd, I tested in a furnace but I'll double check, I think the other issue was pre existing but I'll look into it as well

I can confirm that shift clicking the hotbar was an issue prior to my changes, I will make another attempt at fixing it but I cannot be certain I will be able to.

As far as I can tell the only issue with furnace (and it also applies to other guis like chests) is spam clicking which I _think_ causes the shift click to be processed by minecraft once the As far as I can tell the only issue with furnace (and it also applies to other guis like chests) is spam clicking which I _think_ causes the shift click to be processed by minecraft once the item is moved to the hotbar. I have no idea how to affect this with how the current code works though since the event is different from minecraft's and can't be easily cancelled (plus I'd be worried about potentially cancelling packets w/ watchdog).item is moved to the hotbar. I have no idea how to affect this with how the current code works though since the event is different from minecraft's and can't be easily cancelled (plus I'd be worried about potentially cancelling packets w/ watchdog).

2024-07-28 07:40 UTC, NopoTheGamer approved these changes

2024-08-03 16:08 UTC, nea89o approved these changes

2024-08-04 14:04 UTC, merged