Fix cookie warning
NotEnoughUpdates/NotEnoughUpdates pull request #1201
Opened 2024-06-05 14:58 UTC by NopoTheGamer

also adds the footer to the tablist lines

2024-06-05 15:17 UTC, NopoTheGamer commented
Fixes https://github.com/NotEnoughUpdates/NotEnoughUpdates/issues/1063

2024-06-07 12:57 UTC, jani270 commented on src/main/java/io/github/moulberry/notenoughupdates/util/TabListUtils.java
> +			//System.out.println();
```suggestion
```

2024-06-07 12:57 UTC, jani270 commented
Worked for me cant say much about the code tho

2024-07-06 14:18 UTC, nea89o requested changes

2024-07-06 14:18 UTC, nea89o commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
> +					}
We already have another method (getMinutesRemaining) doing practically the same. I think we should join them.

2024-07-07 08:43 UTC, Lulonaut approved these changes

2024-07-07 13:00 UTC, nea89o approved these changes

2024-07-07 13:08 UTC, merged