Fix Item Cooldown not working for Starred Spirit Mask
NotEnoughUpdates/NotEnoughUpdates pull request #1219
Opened 2024-06-26 15:20 UTC by jani270

2024-06-27 00:49 UTC, NopoTheGamer requested changes

2024-06-27 00:49 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCooldowns.java
> +			internalname.equals("SPIRIT_MASK") || internalname.equals("STARRED_SPIRIT_MASK")) {
```suggestion
		if (NotEnoughUpdates.INSTANCE.config.itemOverlays.spiritAbility &&
			(internalname.equals("SPIRIT_MASK") || internalname.equals("STARRED_SPIRIT_MASK"))) {
```

2024-07-02 15:54 UTC, Lulonaut approved these changes

2024-07-06 11:22 UTC, NopoTheGamer approved these changes

2024-07-06 11:22 UTC, merged