Add accessory bag overlay features
NotEnoughUpdates/NotEnoughUpdates pull request #1269
Opened 2024-07-24 23:43 UTC by Madeleaan

Currently includes:

- sort missing by MP
- highlight dupes
- make overall prettier
- in missing name + price
- on hover same as minions
- dont highlight missing deletors & compactors
- missing show only highest tiers

2024-07-27 01:58 UTC, NopoTheGamer commented
opened it once, it said i was missing every talisman
opened it again, no missing talismans rendered https://hst.sh/raw/opowegakiv

2024-07-27 02:22 UTC, NopoTheGamer requested changes

2024-07-27 02:22 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/miscgui/AccessoryBagOverlay.java
> +				"§eCtrl+Click to learn more!"
these shouldnt say the same thing

2024-07-27 02:22 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/miscgui/AccessoryBagOverlay.java
> +				NotEnoughUpdates.INSTANCE.trySendCommand("/ahs " + displayname);
you need to get rid of the *

2024-07-27 02:22 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/miscgui/AccessoryBagOverlay.java
> +		);
```suggestion
		AccessorGuiContainer accessor = (AccessorGuiContainer) Minecraft.getMinecraft().currentScreen;
		int guiLeft = accessor.getGuiLeft();
		int guiTop = accessor.getGuiTop();
```

also in the other place its used

2024-07-27 02:22 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/miscgui/AccessoryBagOverlay.java
> +						int contact = data.get("abiphone").getAsJsonObject().get("active_contacts").getAsJsonArray().size();
also save this to config

2024-07-27 02:22 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/miscgui/AccessoryBagOverlay.java
> +	private static final int TAB_MISSING = 3;
this could probably be an enum

2024-07-27 02:27 UTC, NopoTheGamer commented
you could probably factor in the "current bonus" to the stats, it seems pretty standardized
![image](https://github.com/user-attachments/assets/9cdc2d80-3c0a-40aa-85e1-454e70d878b0)


also missing a few stats, might have to make a second page
![image](https://github.com/user-attachments/assets/cedd1a54-f3b4-44fb-8d05-2f1d9676f616)
![image](https://github.com/user-attachments/assets/5bec12ff-fef1-43fe-af5e-00ad398bce3f)
![image](https://github.com/user-attachments/assets/8ddd950c-22eb-4ae7-8507-0a8088c36f20)
![image](https://github.com/user-attachments/assets/52fccfd8-bba8-4195-aadb-551385c29d97)
Basically you could add all the stats from /equipment

2024-07-27 09:10 UTC, Madeleaan commented on src/main/java/io/github/moulberry/notenoughupdates/miscgui/AccessoryBagOverlay.java
> +				"§eCtrl+Click to learn more!"
shit i forgot to change the string

2024-07-27 21:53 UTC, Madeleaan commented
> opened it once, it said i was missing every talisman opened it again, no missing talismans rendered https://hst.sh/raw/opowegakiv

Sounds like it didnt load correctly the first time and you scrolled to a page that was beyond the last page it should show when it loads correctly, added an extra check

2024-07-27 22:19 UTC, Madeleaan commented on src/main/java/io/github/moulberry/notenoughupdates/miscgui/AccessoryBagOverlay.java
> +	public static boolean hasConsuedRiftPrism() {
Hopefully did it right

2024-08-01 10:51 UTC, NopoTheGamer approved these changes

2024-08-03 15:29 UTC, nea89o approved these changes

2024-08-03 15:29 UTC, nea89o commented on src/main/resources/assets/notenoughupdates/accessory_bag_overlay_v2.png
![image](https://github.com/user-attachments/assets/191ea23d-9847-4926-a267-c1ae20e2431f)
Maybe this tab could blend in better.

2024-08-03 15:50 UTC, merged