meta: Fix ah and bz search not working without cookie
NotEnoughUpdates/NotEnoughUpdates pull request #1307
Opened 2024-08-09 08:52 UTC by NopoTheGamer

2024-08-11 11:41 UTC, nea89o commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/AuctionSearchOverlay.java
> +				}
```suggestion
				ListIterator<String> words = SPACE_SPLITTER.splitToList(search).listIterator();
				StringBuilder line0 = new StringBuilder();
				while (words.hasNext() ){
					String word = words.next();
					if (line0.length() + word.length() > 15) {
						words.previous();
						break;
					}
					line0.append(word).append(' ');
				}
				StringBuilder line1 = new StringBuilder();
				while (words.hasNext() ){
					String word = words.next();
					if (line1.length() + word.length() > 15) {
						break;
					}
					line1.append(word).append(' ');
				}
```

2024-08-11 11:46 UTC, nea89o requested changes
I really don't like that we mix the static and non static uses of this class. the rendering related methods (relating to the screen) should really be in its own class. Having a subscribe event on that same screen instance is just overloading that classes functionality.

I also really need to say that we cant just copy over code. OOP exists, we can just use `extends SearchOverlayScreen` and put most of the code in that one.

2024-08-11 12:04 UTC, nea89o commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/AuctionSearchOverlay.java
> +				}
This whole thing could also be a single regex: `(.{0,15})( (.{0,15}))?` or something along those lines

2024-08-11 13:04 UTC, NopoTheGamer commented
> we can just use `extends SearchOverlayScreen` and put most of the code in that one.

I sorta just moved all the GUI code into the 1 file, the individual overlays still have the subscribe events but I think it makes sense this way

2024-08-12 00:11 UTC, nea89o approved these changes

2024-08-12 16:35 UTC, Lulonaut approved these changes

2024-08-13 13:16 UTC, merged