Update pet in /equipment
NotEnoughUpdates/NotEnoughUpdates pull request #147
Opened 2022-05-21 19:52 UTC by Lulonaut

This took me way too long

2022-05-22 04:05 UTC, NopoTheGamer approved these changes

2022-05-22 09:05 UTC, DeDiamondPro approved these changes

2022-05-23 12:58 UTC, romangraef requested changes

2022-05-23 12:58 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PetInfoOverlay.java
> +								}
We already have a Util function `XPInformation#getPetLevel` for this

2022-05-24 18:24 UTC, romangraef approved these changes

2022-05-25 01:37 UTC, NopoTheGamer approved these changes

2022-05-25 05:30 UTC, DeDiamondPro approved these changes

2022-05-25 05:30 UTC, merged