Adding skill overlays and hotm stuff in pv + other minor stuff
NotEnoughUpdates/NotEnoughUpdates pull request #15
Opened 2021-10-29 06:03 UTC by nopothegamer

https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/a62ebaaf51b8aee37631534009a7d2d944c8de6d/Update%20Notes/2.1.md

2021-10-29 18:23 UTC, IRONM00N commented on build.gradle
> -version = "2.0-PRE"
just change this to `2.1-REL`

2021-10-29 18:25 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/NEUEventListener.java
> +        if ((Keyboard.isKeyDown(Keyboard.KEY_NUMPAD1) && Keyboard.isKeyDown(Keyboard.KEY_NUMPAD4) && Keyboard.isKeyDown(Keyboard.KEY_NUMPAD9) || NotEnoughUpdates.INSTANCE.config.hidden.bHopBan)) {
please don't add something called bhop, there will be some non on the forums complaining about it

2021-10-29 18:27 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/commands/Commands.java
> +    SimpleCommand bHopCommand = new SimpleCommand("neubhop", new SimpleCommand.ProcessCommandRunnable() {
no

2021-10-31 08:54 UTC, DeDiamondPro requested changes
I'm in with iron that neubhop isn't a good idea because forum nerds

2021-11-01 08:23 UTC, DeDiamondPro approved these changes

2021-11-02 10:22 UTC, IRONM00N approved these changes

2021-11-02 10:22 UTC, merged