quiver info in pv
NotEnoughUpdates/NotEnoughUpdates pull request #210
Opened 2022-08-07 19:52 UTC by Lulonaut

![image](https://user-images.githubusercontent.com/67191924/183308732-5d63abdf-eaa2-435b-9c98-c2149f4b49f3.png)

2022-08-09 02:13 UTC, NopoTheGamer approved these changes
ok

2022-08-09 10:46 UTC, DeDiamondPro submitted a review, later dismissed
Very cool, I rate 5 janis out of 10 bananas

2022-08-11 10:08 UTC, NopoTheGamer requested changes
after testing the pr i have noticed it crashes my game

2022-08-11 12:35 UTC, NopoTheGamer approved these changes

2022-08-11 15:07 UTC, DeDiamondPro submitted a review, later dismissed

2022-08-11 22:27 UTC, NopoTheGamer approved these changes

2022-08-12 07:51 UTC, DeDiamondPro approved these changes

2022-08-13 07:23 UTC, DeDiamondPro approved these changes

2022-08-13 08:07 UTC, DoKM approved these changes

2022-08-13 08:14 UTC, NopoTheGamer approved these changes

2022-08-13 08:14 UTC, merged