Fix enchantment table overlay
NotEnoughUpdates/NotEnoughUpdates pull request #238
Opened 2022-08-20 01:14 UTC by NopoTheGamer

2022-08-26 14:56 UTC, DeDiamondPro approved these changes

2022-08-26 15:09 UTC, DeDiamondPro requested changes
L nopo

2022-08-26 15:09 UTC, DeDiamondPro commented on src/main/java/io/github/moulberry/notenoughupdates/miscgui/hex/ItemType.java
> +}
Shouldn't this be part of repo? might need to be updated later with new updates

2022-08-26 15:13 UTC, DeDiamondPro submitted a review, later dismissed

2022-09-02 15:04 UTC, Lulonaut approved these changes
seems to work (I do not have the hex thing)

2022-09-09 06:07 UTC, NopoTheGamer commented
why must that dismiss reviews :sob:

2022-09-09 13:53 UTC, Lulonaut approved these changes

2022-09-09 19:11 UTC, romangraef approved these changes

2022-09-11 12:04 UTC, hannibal00212 commented
Don't gonna review or approve a 4700 lines class

2022-09-11 12:05 UTC, NopoTheGamer commented
> Don't gonna review or approve a 4700 lines class

:+1: I'll just get jani to look at the code then Kappa

2022-09-11 12:06 UTC, jani270 commented
> > Don't gonna review or approve a 4700 lines class
> 
> 👍 I'll just get jani to look at the code then Kappa

Ok i will

2022-09-12 16:31 UTC, hannibal00212 approved these changes
I dont like big classes

2022-09-12 16:31 UTC, merged