misc dungeon profit changes
NotEnoughUpdates/NotEnoughUpdates pull request #240
Opened 2022-08-20 13:58 UTC by efefury

- changed the location of buttons when in dungeon profit overlay
- added a warning if derpy is mayor
![image](https://user-images.githubusercontent.com/69400149/185749640-b0ad014d-e32e-4397-b36d-33e9a6aacbe8.png)

2022-08-20 16:50 UTC, Lulonaut requested changes

2022-08-20 16:50 UTC, Lulonaut commented on src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
> +				throw new RuntimeException(e);
Crashing the users game when something goes wrong with the request does not seem like a good idea

2022-08-20 16:50 UTC, Lulonaut commented on src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
> +	public static JsonObject getCurrentMayor() throws ExecutionException, InterruptedException {
I would move this to SBInfo.java, does not seem like a Utils thing

2022-08-20 18:46 UTC, romangraef requested changes

2022-08-20 18:46 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
> +		return hypixelApiAsync.get();
Can we not use blocking methods in a `tick()` method?

2022-08-20 19:10 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
> +	public void getCurrentMayor() throws ExecutionException, InterruptedException {
Do we still throw those exceptions? Also i feel like we could give this function a better name now that it doesnt return anything anymore

2022-08-20 19:19 UTC, romangraef approved these changes

2022-08-20 19:20 UTC, Lulonaut approved these changes

2022-08-21 10:36 UTC, NopoTheGamer approved these changes

2022-08-21 10:37 UTC, merged