Readme changes
NotEnoughUpdates/NotEnoughUpdates pull request #26
Opened 2021-11-25 18:26 UTC by jani270

Ello
- Changed Patreon to downloads badge (moul bad, me sad)
- Made much more thing linked to features list

2021-11-26 05:36 UTC, nopothegamer approved these changes

2021-11-27 15:29 UTC, DeDiamondPro requested changes
Add a check to see if the "runes" compound actually exists because hypixel weird and if they change it -> crash

2021-11-27 15:53 UTC, DeDiamondPro approved these changes

2021-11-28 10:35 UTC, nopothegamer approved these changes

2021-11-28 22:10 UTC, merged