Store auctionable items locally to only show price warning if the item can actually have a price
NotEnoughUpdates/NotEnoughUpdates pull request #29
Opened 2021-12-04 15:53 UTC by Lulonaut

This stores the internal names of all items that can be auctioned (from the Moulberry api) and only shows the warning if the item is in that list.

If the api is down on the first launch with this it will not work and still show the warning everywhere, with an added message.

After that if API is down it will use this List to check if the price info should be shown. (Skyblock menu is always blacklisted)

2021-12-05 02:07 UTC, IRONM00N requested changes

2021-12-05 02:07 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/ItemPriceInformation.java
> +                tooltip.add(message + "\n(It is not known if this item even has price info)");
I would make this message shorter

2021-12-09 17:49 UTC, DeDiamondPro reviewed
Why do you disable the price in "SKYBLOCK_MENU"?

2021-12-09 19:11 UTC, DeDiamondPro approved these changes

2021-12-11 04:08 UTC, nopothegamer approved these changes

2021-12-11 04:13 UTC, merged