the people in #general said this would fix a crash
NotEnoughUpdates/NotEnoughUpdates pull request #317
Opened 2022-09-26 14:30 UTC by NopoTheGamer

2022-09-26 14:33 UTC, Ascynx commented
soon:tm:

2022-09-26 14:43 UTC, romangraef requested changes
0 <= actualIndex && actualIndex < searchedItems.size()

2022-09-26 14:44 UTC, romangraef commented
the !searchedItems.isEmpty() is completely useless, since searchedItems.isEmpty() implies searchedItems.size() is 0, therefore any index at or above 0 would already fail the condition before, and index below 0 will still fail the new condition.

2022-09-26 14:49 UTC, romangraef approved these changes

2022-09-26 14:52 UTC, Lulonaut approved these changes

2022-09-27 02:15 UTC, IRONM00N approved these changes

2022-09-27 02:16 UTC, merged