Add custom keystore and refactor HypixelApi.java
NotEnoughUpdates/NotEnoughUpdates pull request #318
Opened 2022-09-27 04:00 UTC by romangraef

2022-09-27 09:39 UTC, Ascynx approved these changes
~~lessgo~~, should probably close connection after it's not used anymore (see infer check).

2022-09-28 10:13 UTC, Lulonaut approved these changes

2022-09-28 16:17 UTC, Mqisty commented
looks god to me ! :fire: :+1: :100:

2022-09-28 16:18 UTC, Ascynx submitted a review, later dismissed
:scream: :scream: :scream: :scream:

2022-09-28 16:19 UTC, Mqisty submitted a review, later dismissed
looks bad to me ! :fire_extinguisher: :-1: :1234:

2022-09-28 17:43 UTC, Lulonaut approved these changes

2022-09-29 04:43 UTC, NopoTheGamer requested changes

2022-09-29 04:43 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
> +									break;
Remove the break as it makes the profile not show in the profile selector

2022-09-29 14:48 UTC, hannibal002 approved these changes

2022-09-29 14:57 UTC, NopoTheGamer approved these changes

2022-09-29 14:59 UTC, Lulonaut approved these changes

2022-09-29 15:25 UTC, merged