Trophy Fish Total Count
NotEnoughUpdates/NotEnoughUpdates pull request #338
Opened 2022-10-04 15:30 UTC by Vixid1

![image](https://user-images.githubusercontent.com/52578495/193861650-6c5ed4aa-b5f2-449f-9b11-e98ded3a257d.png)

Added trophy fish total count to trophy fish, along with formatted numbers for readability.

2022-10-04 15:35 UTC, romangraef commented
Who is this screenshot from and can we stop them

2022-10-04 15:38 UTC, Vixid1 commented
> Who is this screenshot from and can we stop them

It’s from DeathStreeks, just needed someone who I know had a lot of trophy fish lol

2022-10-04 15:40 UTC, romangraef approved these changes

2022-10-04 15:46 UTC, Lulonaut submitted a review, later dismissed

2022-10-04 15:55 UTC, efefury requested changes

2022-10-04 15:55 UTC, efefury commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/trophy/TrophyFishPage.java
> +		tooltip.add(EnumChatFormatting.GRAY + "Total: " + EnumChatFormatting.GOLD + NUMBER_FORMAT.format((trophyFishList.get(name).getTotal())));
Why are there two `(`?

2022-10-04 15:58 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/trophy/TrophyFishPage.java
> +		tooltip.add(EnumChatFormatting.GRAY + "Total: " + EnumChatFormatting.GOLD + NUMBER_FORMAT.format((trophyFishList.get(name).getTotal())));
all the cool kids use two `(`

2022-10-04 17:26 UTC, Vixid1 commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/trophy/TrophyFishPage.java
> +		tooltip.add(EnumChatFormatting.GRAY + "Total: " + EnumChatFormatting.GOLD + NUMBER_FORMAT.format((trophyFishList.get(name).getTotal())));
was accidental, fixed in new commit

2022-10-04 23:45 UTC, hannibal002 approved these changes

2022-10-21 01:09 UTC, NopoTheGamer approved these changes

2022-10-21 01:11 UTC, IRONM00N approved these changes

2022-10-21 01:11 UTC, merged