Miscellaneous Typos
NotEnoughUpdates/NotEnoughUpdates pull request #339
Opened 2022-10-04 20:06 UTC by walkerselby

Fixed Random Typos
Standardized spelling of SkyBlock to "SkyBlock", as indicated by Hypixel
Standardized capitalization of NEU to NEU from neu and Neu in many places
Edited messages for clarity
Expanded OF to Optifine for clarity
Other miscellaneous typos -- see commits.

2022-10-04 20:06 UTC, romangraef commented
>  Standardized spelling of SkyBlock to "SkyBlock", as indicated by Hypixel
We should do the same for HyPixel

2022-10-04 20:07 UTC, jani270 commented
> > Standardized spelling of SkyBlock to "SkyBlock", as indicated by Hypixel
> 
> We should do the same for HyPixel

No.

2022-10-04 20:08 UTC, romangraef commented
> No.

so sad

2022-10-04 20:10 UTC, walkerselby commented
>  We should do the same for HyPixel
<img width="351" alt="Screenshot 2022-10-04 at 1 09 19 PM" src="https://user-images.githubusercontent.com/29870899/193916249-e8ca15a9-6aef-4741-a50d-3b5d1be5ef75.png">
No.

2022-10-04 21:35 UTC, IRONM00N commented
> >  Standardized spelling of SkyBlock to "SkyBlock", as indicated by Hypixel
> 
> 
> 
> We should do the same for HyPixel
> 
> 

:trollface:

2022-10-04 22:03 UTC, MicrocontrollersDev requested changes
also i agree with the jani i don't care what hypixel says, "SkyBlock" is wrong.

2022-10-04 22:03 UTC, MicrocontrollersDev commented on src/main/java/io/github/moulberry/notenoughupdates/commands/misc/CosmeticsCommand.java
> +				"NEU Cosmetics do not work with Optifine Fast Render. Go to ESC > Options > Video Settings > Performance > Fast Render to disable it."));
```suggestion
				"NEU Cosmetics do not work with OptiFine Fast Render. Go to ESC > Options > Video Settings > Performance > Fast Render to disable it."));
```

2022-10-04 22:03 UTC, MicrocontrollersDev commented on src/main/java/io/github/moulberry/notenoughupdates/commands/profile/ViewProfileCommand.java
> +				"Some parts of the profile viewer do not work with Optifine Fast Render. Go to ESC > Options > Video Settings > Performance > Fast Render to disable it."));
```suggestion
				"Some parts of the profile viewer do not work with OptiFine Fast Render. Go to ESC > Options > Video Settings > Performance > Fast Render to disable it."));
```

2022-10-04 22:14 UTC, walkerselby commented
> also i agree with the jani i don't care what hypixel says, "SkyBlock" is wrong.

I am fine with either way, we just had 33% skyblock, 33% Skyblock and 33# SkyBlock, so I was going for something consistent. If we favor Skyblock,
I can change it to that when I am back at my desk.

2022-10-11 17:36 UTC, MicrocontrollersDev submitted a review, later dismissed
while i disagree with hypixel’s direction with SkyBlock, everything looks good

2022-10-19 08:00 UTC, hannibal002 approved these changes

2022-10-19 08:03 UTC, hannibal002 requested changes
merge needed

2022-10-19 15:38 UTC, Lulonaut approved these changes
HyPixel SkyBlock

2022-10-19 15:45 UTC, hannibal002 approved these changes
HyBlock SkyPixel

2022-10-19 15:45 UTC, MicrocontrollersDev approved these changes

2022-10-19 22:07 UTC, romangraef approved these changes

2022-10-19 22:07 UTC, merged