Support for cata 50+ and class average.
NotEnoughUpdates/NotEnoughUpdates pull request #349
Opened 2022-10-10 14:50 UTC by Vixid1

Saw in NEU 2.1.1 jani added this as a to-do so I did it. Along with some other things.

Added:

- Support for cata and class levels above 50
- Added class average bar below classes
- Show exact remaining xp when hovering over 'Until Cata x:'
- Also fixed the bounds for clicking the text box for calculating xp to cata level since it was off a bit

![image](https://user-images.githubusercontent.com/52578495/194893187-9a2b83cf-9b33-48a5-9219-514b89b2ff74.png)

![image](https://user-images.githubusercontent.com/52578495/194893343-9e9a0738-d319-4c52-81ef-15cb281a11a9.png)

![image](https://user-images.githubusercontent.com/52578495/194893284-762ae966-7113-4826-8065-2b36b5353527.png)

![image](https://user-images.githubusercontent.com/52578495/194893445-402f41f2-4dc0-4fd3-8a5c-22c03d23d5c9.png)

2022-10-19 08:21 UTC, NopoTheGamer commented
![image](https://user-images.githubusercontent.com/40329022/196636640-edc8d95c-a6eb-4098-bed0-dee5fb9516ba.png)
I dont think you can get above level 50 class

2022-10-21 07:46 UTC, hannibal002 approved these changes

2022-10-21 08:52 UTC, hannibal002 requested changes
After trying to merge with master, I got this error:

`MixinGuiTextField.java:83: warning: Cannot find method mapping for @At(INVOKE.<target>) 'Lcom/google/common/base/Predicate;apply(Ljava/lang/Object;)Z'`

2022-10-28 23:03 UTC, romangraef approved these changes

2022-10-29 22:26 UTC, hannibal002 approved these changes

2022-10-30 10:27 UTC, NopoTheGamer approved these changes

2022-10-30 10:27 UTC, merged