Ctrl + Z and Ctrl + Y support
NotEnoughUpdates/NotEnoughUpdates pull request #358
Opened 2022-10-11 21:53 UTC by Ascynx

Every action on the text of a text field can be undone and redone using Ctrl + z and Ctrl + Y.

2022-10-11 22:01 UTC, Ascynx commented
Currently, acting after undoing or redoing an action will append at the end of the stack. I'm still debating with myself wether I want to keep it that way or cut the stack to where the last redo/undo last happened.

2022-10-19 08:16 UTC, hannibal002 requested changes

2022-10-19 08:16 UTC, hannibal002 commented on src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
> +
can we remove this extra line?

2022-10-19 08:17 UTC, Ascynx commented on src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
> +
Can do when I'm back home

2022-10-20 09:16 UTC, NopoTheGamer approved these changes

2022-10-20 10:15 UTC, hannibal002 approved these changes

2022-10-21 01:25 UTC, IRONM00N approved these changes
ctrl + shift + z my beloved

2022-10-21 01:25 UTC, merged