Added repo parserer for the draconic table thingy
NotEnoughUpdates/NotEnoughUpdates pull request #365
Opened 2022-10-14 10:53 UTC by NopoTheGamer

+ changed the thingy jani wanted

2022-10-28 23:10 UTC, romangraef requested changes
if youre really gonna be this averse to creating new files, maybe at least use recipegenerator instead of renderlistener, please nopo (or at fucking least also make a function instead of just yet another if branch)

2022-11-01 22:21 UTC, hannibal002 commented
Is this still active? Maybe make it a draft for clarification?

2022-11-02 05:33 UTC, NopoTheGamer commented
> Is this still active? Maybe make it a draft for clarification?

should be good to go

2022-11-02 15:49 UTC, Lulonaut approved these changes

2022-11-02 18:45 UTC, hannibal002 approved these changes

2022-11-18 13:42 UTC, romangraef approved these changes

2022-11-20 12:07 UTC, merged