lulonaut bad
NotEnoughUpdates/NotEnoughUpdates pull request #367
Opened 2022-10-14 13:39 UTC by efefury

2022-10-14 13:41 UTC, jani270 requested changes

2022-10-14 13:41 UTC, jani270 commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Dungeons.java
> +		name = "Open Pv On Join ",
Please remove the space at the end

2022-10-14 13:43 UTC, jani270 commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Dungeons.java
> +		name = "Open Pv On Join ",
and please name it better

2022-10-14 13:43 UTC, Ascynx commented
![:watching:](https://cdn.discordapp.com/emojis/941469316279332864.webp?size=96&quality=lossless)

2022-10-19 08:13 UTC, NopoTheGamer approved these changes

2022-10-19 09:45 UTC, hannibal002 commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Dungeons.java
> +		name = "Add Pv Command Click on Party Finder Join",
Need to shorten this name

2022-10-19 09:46 UTC, hannibal002 commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Dungeons.java
> +		name = "Add Pv Command Click on Party Finder Join",
![image](https://user-images.githubusercontent.com/24389977/196657535-5cc9a346-0fd1-43c3-8bce-beac1d71f5b2.png)

2022-10-21 01:17 UTC, NopoTheGamer submitted a review, later dismissed

2022-11-05 10:48 UTC, efefury commented
:pray:

2022-12-30 18:25 UTC, closed without merging