Big trollers
NotEnoughUpdates/NotEnoughUpdates pull request #396
Opened 2022-10-22 07:47 UTC by Ascynx

Have you ever thought what would happen if you had a mod like skytils that blocks ``/coopadd`` and got angry because when you used ``/hypixelcommand:coopadd`` you got your profile stolen, well no more.
Because with this pull request NEU is gonna berate you for using a command with the **/hypixelcommand:** prefix.

[NotEnoughUpdates] You just executed /hypixelcommand:coopadd. Use /coopadd Like a civilised individual

2022-10-22 07:49 UTC, NopoTheGamer approved these changes
I cant wait for this to break some random click command that hypixel will send later in 2021

2022-10-22 07:52 UTC, shuuyu commented
I love 2021

2022-10-22 14:54 UTC, romangraef commented
I guess i should remove the -obf artifacts?

2022-10-22 14:56 UTC, NopoTheGamer commented
> I guess i should remove the -obf artifacts?

what?

2022-10-22 15:00 UTC, romangraef commented
wrong chat

2022-10-23 20:02 UTC, romangraef requested changes
I don't really like this. If you want to keep this, maybe mixinto GuiChat/GuiChatNew so that only user sent commands cause this (and not commands ran by click actions)

2022-10-24 01:00 UTC, IRONM00N requested changes
This seems completely unnecessary, if Skytils wants to block `/coopadd` add then they can block `/hypixelcommand:coopadd` too. Unless I am misunderstanding something, I don't see how it is NEU's job to modify Skytil's features.

2022-10-24 05:09 UTC, shuuyu commented
> This seems completely unnecessary, if Skytils wants to block `/coopadd` add then they can block `/hypixelcommand:coopadd` too. Unless I am misunderstanding something, I don't see how it is NEU's job to modify Skytil's features.

This essentially applies to every command on the server, not just coopadd. This means that it can override features regardless of use case. It's weird because it only applies to some commands, like warp and coop commands, but `/hypixelcommand:api new` doesn't work, as well as `/hypixelcommand:apinew`.

Here's the full list:
/hypixelcommand:<auth>, /hypixelcommand:ac, /hypixelcommand:acceptinvite, /hypixelcommand:achat, /hypixelcommand:achrewards, /hypixelcommand:activeeffects, /hypixelcommand:advent, /hypixelcommand:adventmenu, /hypixelcommand:ah, /hypixelcommand:ai, /hypixelcommand:anvil, /hypixelcommand:anvilmenu, /hypixelcommand:atlas, /hypixelcommand:attributemenu, /hypixelcommand:attributetransfer, /hypixelcommand:auction, /hypixelcommand:auctions, /hypixelcommand:av, /hypixelcommand:back, /hypixelcommand:baz, /hypixelcommand:bazaar, /hypixelcommand:be, /hypixelcommand:bestiary, /hypixelcommand:bingo, /hypixelcommand:bz, /hypixelcommand:caa, /hypixelcommand:calendar, /hypixelcommand:cb, /hypixelcommand:cc, /hypixelcommand:cchat, /hypixelcommand:chatprompt, /hypixelcommand:chatreport, /hypixelcommand:checkreputation, /hypixelcommand:claimdarewards, /hypixelcommand:claimitem, /hypixelcommand:clearstash, /hypixelcommand:co, /hypixelcommand:collection, /hypixelcommand:collectionlog, /hypixelcommand:collections, /hypixelcommand:combatinfo, /hypixelcommand:configvisualizer, /hypixelcommand:coop, /hypixelcommand:coopadd, /hypixelcommand:coopchat, /hypixelcommand:coopcheck, /hypixelcommand:coopkick, /hypixelcommand:coopmanage, /hypixelcommand:coopmode, /hypixelcommand:coopparty, /hypixelcommand:coopsalvage, /hypixelcommand:coopview, /hypixelcommand:cr, /hypixelcommand:craft, /hypixelcommand:craftedgenerators, /hypixelcommand:craftingmenu, /hypixelcommand:craftingtable, /hypixelcommand:creport, /hypixelcommand:customstatus, /hypixelcommand:deathcount, /hypixelcommand:dialogue, /hypixelcommand:disableautopickupmsg, /hypixelcommand:dontpersistrecording, /hypixelcommand:dungeonlootinternal, /hypixelcommand:e, /hypixelcommand:ec, /hypixelcommand:echest, /hypixelcommand:effects, /hypixelcommand:eg, /hypixelcommand:emoji, /hypixelcommand:emojihelp, /hypixelcommand:emojis, /hypixelcommand:emotes, /hypixelcommand:enchantingtable, /hypixelcommand:enchantingtablemenu, /hypixelcommand:enchantments, /hypixelcommand:enchantmentsguide, /hypixelcommand:enchantmenttable, /hypixelcommand:enchantmenttablemenu, /hypixelcommand:enchants, /hypixelcommand:enderchest, /hypixelcommand:enterthecrystalhollows, /hypixelcommand:equipment, /hypixelcommand:et, /hypixelcommand:etable, /hypixelcommand:evacuate, /hypixelcommand:events, /hypixelcommand:fishingbosses, /hypixelcommand:fourinarow, /hypixelcommand:gamehistory, /hypixelcommand:games, /hypixelcommand:garry, /hypixelcommand:getoffmyface, /hypixelcommand:glow, /hypixelcommand:guest, /hypixelcommand:guestlocation, /hypixelcommand:headstatus, /hypixelcommand:hecks, /hypixelcommand:hello, /hypixelcommand:hex, /hypixelcommand:hgl, /hypixelcommand:hi, /hypixelcommand:hologramline, /hypixelcommand:hotm, /hypixelcommand:hub, /hypixelcommand:internalrankgift, /hypixelcommand:internalrankgiftcheck, /hypixelcommand:invite, /hypixelcommand:invspy, /hypixelcommand:islandname, /hypixelcommand:islandrank, /hypixelcommand:itemreport, /hypixelcommand:joinadvertisedgame, /hypixelcommand:joindungeon, /hypixelcommand:kitme, /hypixelcommand:lang, /hypixelcommand:language, /hypixelcommand:leavequeue, /hypixelcommand:level, /hypixelcommand:levels, /hypixelcommand:loadresourcepack, /hypixelcommand:loadresourcepackimmediately, /hypixelcommand:lq, /hypixelcommand:map, /hypixelcommand:mapfeedback, /hypixelcommand:maskrank, /hypixelcommand:maxcollections, /hypixelcommand:mmreport, /hypixelcommand:mp, /hypixelcommand:msgreport, /hypixelcommand:myfilter, /hypixelcommand:mygames, /hypixelcommand:mypos, /hypixelcommand:myposition, /hypixelcommand:networkbooster, /hypixelcommand:nick, /hypixelcommand:openachievementmenu, /hypixelcommand:openduelpickpage, /hypixelcommand:opengamesettings, /hypixelcommand:openpunchmessagemenu, /hypixelcommand:openresourcepackbook, /hypixelcommand:opme, /hypixelcommand:ov, /hypixelcommand:particlequality, /hypixelcommand:pastgames, /hypixelcommand:persistrecording, /hypixelcommand:pet, /hypixelcommand:petmenu, /hypixelcommand:pets, /hypixelcommand:petsmenu, /hypixelcommand:pickupstash, /hypixelcommand:placeoneblockfor, /hypixelcommand:playsong, /hypixelcommand:playtime, /hypixelcommand:potions, /hypixelcommand:pq, /hypixelcommand:profile, /hypixelcommand:profiles, /hypixelcommand:pt, /hypixelcommand:purchasecrystallhollowspass, /hypixelcommand:pvpinfo, /hypixelcommand:quality, /hypixelcommand:questlog, /hypixelcommand:quests, /hypixelcommand:rankcolor, /hypixelcommand:rankcolour, /hypixelcommand:recentgames, /hypixelcommand:recipebook, /hypixelcommand:recipemenu, /hypixelcommand:recipes, /hypixelcommand:regennetherquests, /hypixelcommand:rej, /hypixelcommand:rejoin, /hypixelcommand:replay, /hypixelcommand:replays, /hypixelcommand:report, /hypixelcommand:reporttext, /hypixelcommand:reportworld, /hypixelcommand:resource, /hypixelcommand:resourcebook, /hypixelcommand:resourcehelp, /hypixelcommand:resourcepackbook, /hypixelcommand:resourcepackhelp, /hypixelcommand:rewards, /hypixelcommand:roominfo, /hypixelcommand:sacks, /hypixelcommand:savethejerrys, /hypixelcommand:sax, /hypixelcommand:sbkick, /hypixelcommand:sbkickall, /hypixelcommand:sblevel, /hypixelcommand:sblevels, /hypixelcommand:sbmenu, /hypixelcommand:sbmod, /hypixelcommand:sbwarptoken, /hypixelcommand:scg, /hypixelcommand:seacreature, /hypixelcommand:seacreatureguide, /hypixelcommand:secretinstance, /hypixelcommand:selectnpcoption, /hypixelcommand:setguestlocation, /hypixelcommand:setguestspawn, /hypixelcommand:sethome, /hypixelcommand:setlang, /hypixelcommand:setlanguage, /hypixelcommand:setselectedfaction, /hypixelcommand:setspawn, /hypixelcommand:setspawnlocation, /hypixelcommand:settings, /hypixelcommand:share, /hypixelcommand:sisyphus, /hypixelcommand:skillmenu, /hypixelcommand:skills, /hypixelcommand:skillsmenu, /hypixelcommand:skyblocklevel, /hypixelcommand:skyblocklevels, /hypixelcommand:smp, /hypixelcommand:social, /hypixelcommand:socialinternal, /hypixelcommand:socialoptions, /hypixelcommand:spawnlocation, /hypixelcommand:st, /hypixelcommand:stopsong, /hypixelcommand:storage, /hypixelcommand:surveyinternal, /hypixelcommand:t, /hypixelcommand:teleports, /hypixelcommand:textreport, /hypixelcommand:thehex, /hypixelcommand:thiscommandliterallydoesnothing, /hypixelcommand:tictactoe, /hypixelcommand:togglecoopchat, /hypixelcommand:togglemusic, /hypixelcommand:togglerds, /hypixelcommand:trackcombat, /hypixelcommand:trackpvp, /hypixelcommand:trade, /hypixelcommand:tradeaccept, /hypixelcommand:travel, /hypixelcommand:turnoffexclusionnotice, /hypixelcommand:turnoffitemframenotice, /hypixelcommand:undograndarchitect, /hypixelcommand:undozap, /hypixelcommand:versions, /hypixelcommand:viewauction, /hypixelcommand:viewbosscollection, /hypixelcommand:viewcollection, /hypixelcommand:viewcollectionmenu, /hypixelcommand:viewcommissionmilestones, /hypixelcommand:viewcraftingtable, /hypixelcommand:viewdungeonclass, /hypixelcommand:viewdungeontype, /hypixelcommand:viewenderchest, /hypixelcommand:vieweventrewards, /hypixelcommand:viewhotm, /hypixelcommand:viewjournal, /hypixelcommand:viewmuseumrewards, /hypixelcommand:viewpets, /hypixelcommand:viewpetsmenu, /hypixelcommand:viewpotion, /hypixelcommand:viewprofile, /hypixelcommand:viewquestlog, /hypixelcommand:viewrecipe, /hypixelcommand:viewrecipebook, /hypixelcommand:viewsbmenu, /hypixelcommand:viewsettings, /hypixelcommand:viewskill, /hypixelcommand:viewskillmenu, /hypixelcommand:viewstash, /hypixelcomman [...]

2022-10-24 07:29 UTC, Ascynx commented
> I don't really like this. If you want to keep this, maybe mixinto GuiChat/GuiChatNew so that only user sent commands cause this (and not commands ran by click actions)
fair

2022-10-24 08:27 UTC, NopoTheGamer submitted a review, later dismissed
while this is still stupid

2022-10-24 08:32 UTC, NopoTheGamer approved these changes
it is less stupid then before

2022-10-25 22:03 UTC, IRONM00N commented
> > This seems completely unnecessary, if Skytils wants to block `/coopadd` add then they can block `/hypixelcommand:coopadd` too. Unless I am misunderstanding something, I don't see how it is NEU's job to modify Skytil's features.
> 
> This essentially applies to every command on the server, not just coopadd. This means that it can override features regardless of use case. It's weird because it only applies to some commands, like warp and coop commands, but `/hypixelcommand:api new` doesn't work.
> 
> Here's the commands that work

I am aware that this would block all commands beginning with "hypixelcommand", I responded to the description of the pr. 

My point still stands: I do not see any benefit of this pr.

2022-10-25 22:24 UTC, romangraef commented
`/hypixelalias:.º` moment btw

2022-10-25 22:24 UTC, romangraef commented
Im gonna be honest: this pr seems like it will do more harm than good.

2022-10-26 17:22 UTC, hannibal002 commented
Please block all commands containing coopadd instead, or mixin into skytils. But don't touch /hypixelcommand:, that's too harsh of a filter.

Additional, please clarify in the future that you are fixing a skytils Bug with your PR.

2022-10-26 17:24 UTC, closed without merging