Optional Oneconfig support
NotEnoughUpdates/NotEnoughUpdates pull request #401
Opened 2022-10-24 13:32 UTC by romangraef

Still early alpha (not support for subcategories and desyncs with /neu config quite easily)

2022-12-06 22:30 UTC, romangraef commented
@wyvest do you mind checking if the hacks i do in the src/oneconfig source set are okay?

2022-12-13 09:52 UTC, Lulonaut approved these changes
Exiting out of the GUI locations editor sends you back to /neu

The warnings/info in some categories is only partially displayed and without color codes

When opening /neu after changing a setting in OneConfig the slider animation is a bit janky

But overall still usable

2022-12-15 23:02 UTC, romangraef commented
> Exiting out of the GUI locations editor sends you back to /neu

I suppose ill fix that

> The warnings/info in some categories is only partially displayed and without color codes

This is a oneconfig sided issue and not really one i can fix

> When opening /neu after changing a setting in OneConfig the slider animation is a bit janky

I dont really have the goal to support using oneconfig AND moulconfig at the same time, so ill consider this a wontfix for now.

2022-12-22 18:39 UTC, Lulonaut submitted a review, later dismissed

2022-12-31 04:45 UTC, NopoTheGamer submitted a review, later dismissed
works besides what i can only assume is one config issues

2022-12-31 05:12 UTC, Wyvest requested changes

2022-12-31 05:12 UTC, Wyvest commented on src/oneconfig/java/io/github/moulberry/notenoughupdates/compat/oneconfig/OneMoulConfig.java
> +					annotation.desc(), cat, subcategory, 1, InfoType.WARNING
make info size 2 (and do the same to some other options iyw) to avoid text cutting out

2023-01-01 18:41 UTC, Lulonaut submitted a review, later dismissed

2023-01-01 23:25 UTC, NopoTheGamer submitted a review, later dismissed

2023-01-05 09:15 UTC, Pikaahhh commented
balls!

2023-01-05 12:36 UTC, Rattlyy commented
this is actually hot

2023-01-08 12:07 UTC, NopoTheGamer approved these changes

2023-01-11 18:39 UTC, hannibal002 approved these changes

2023-01-11 21:03 UTC, jani270 approved these changes
Hello, nea asked me to replace lulonaut while reviewing this pr because he is on holiday. I will do this but please blame nea if there is smth wrong! I still have no idea what these funny words mean 👍 Also i didnt test this

2023-01-11 21:03 UTC, merged