ctrl +f support
NotEnoughUpdates/NotEnoughUpdates pull request #423
Opened 2022-11-04 21:50 UTC by Lulonaut

for /neu and the search bar

2022-11-04 22:13 UTC, jani270 requested changes

2022-11-04 22:13 UTC, jani270 commented on src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
> +				Minecraft.getMinecraft().thePlayer.addChatMessage(new ChatComponentText(
Utils.addChatMessage 🤓

2022-11-05 08:10 UTC, hannibal002 submitted a review, later dismissed

2022-11-07 10:23 UTC, NopoTheGamer approved these changes

2022-11-08 21:52 UTC, jani270 reviewed
2.1.1.md when

2022-11-09 18:05 UTC, romangraef requested changes
Since someone in discord had problems with this: can this behaviour turned of since some people have bound CTRL+F to drop stack (at least in the search bar)

2022-11-10 17:48 UTC, romangraef approved these changes

2022-11-10 19:26 UTC, hannibal002 approved these changes

2022-11-11 12:38 UTC, NopoTheGamer approved these changes

2022-11-11 12:39 UTC, merged