Added hourly rates and blocks/chest to powder grinding tracker
NotEnoughUpdates/NotEnoughUpdates pull request #429
Opened 2022-11-06 12:33 UTC by KingsMMA

2022-11-06 13:51 UTC, hannibal002 approved these changes
![image](https://user-images.githubusercontent.com/24389977/200174613-62a8263a-04d8-4835-b8e6-c7c108f9f35b.png)
I don't like this feature, it shows how bad I am.

2022-11-07 11:10 UTC, KingsMMA commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
> +	public int powderGrindingPauseTimer = 3;
I can increase the default setting if you want; I used 10 when testing as it gave me time to open chests

2022-11-07 11:13 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
> +	public int powderGrindingPauseTimer = 3;
eh ig?

2022-11-07 12:44 UTC, Ascynx commented
> ![image](https://user-images.githubusercontent.com/24389977/200174613-62a8263a-04d8-4835-b8e6-c7c108f9f35b.png)
> I don't like this feature, it shows how bad I am. 

Same, same 😭

2022-11-07 14:17 UTC, hannibal002 approved these changes

2022-11-09 19:51 UTC, hannibal002 requested changes
![image](https://user-images.githubusercontent.com/24389977/200927309-499e9905-9dcc-475f-b7c5-f3f9ef30c248.png)

Is this my fault? I've started the version again after one day and then some values are negative?

2022-11-10 05:55 UTC, KingsMMA commented
> ![image](https://user-images.githubusercontent.com/24389977/200927309-499e9905-9dcc-475f-b7c5-f3f9ef30c248.png)
> 
> Is this my fault? I've started the version again after one day and then some values are negative?

I've updated saving and loading for the elapsed and blocks mined values.
Do you have multiple tools with compact?
The blocks mined is updated based off of your held tools compact counter, which may have caused the negative values

2022-11-10 19:29 UTC, hannibal002 commented
@KingsMMA sadly yes. You have to compare the compact value AND the item UUID as well. :/

2022-11-25 21:25 UTC, hannibal002 commented
Since no more edits for almost 2 weeks, I move this PR into drafts. @KingsMMA Feel free to open the PR as soon as you think it's ready :)

2023-01-25 18:50 UTC, closed without merging