show price of essence when pressing shift in essence upgrades gui
NotEnoughUpdates/NotEnoughUpdates pull request #440
Opened 2022-11-12 17:05 UTC by Lulonaut

title

2022-11-12 17:20 UTC, romangraef approved these changes

2022-11-15 21:16 UTC, NopoTheGamer requested changes

2022-11-15 21:16 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/recipes/EssenceUpgrades.java
> +					EnumChatFormatting.AQUA + Utils.formatNumberWithDots(tierUpgrade.getEssenceRequired()) + " " + EnumChatFormatting.DARK_GRAY +
make it use system format 🙂

2022-11-24 19:05 UTC, romangraef approved these changes

2022-11-25 09:51 UTC, NopoTheGamer approved these changes

2022-11-25 20:55 UTC, hannibal002 approved these changes

2022-11-25 20:55 UTC, merged