Added Overlaystyle option to powder grinding tracker
NotEnoughUpdates/NotEnoughUpdates pull request #448
Opened 2022-11-26 18:17 UTC by jani270

2022-11-26 18:20 UTC, GodOfProDev approved these changes
cool

2022-11-26 22:54 UTC, jani270 commented
Also yes 2 things in 1 pr idc

2022-11-27 11:04 UTC, Lulonaut submitted a review, later dismissed

2022-11-28 00:12 UTC, romangraef submitted a review, later dismissed

2022-11-28 11:44 UTC, NopoTheGamer requested changes

2022-11-28 11:44 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
> +	public int powderGrindingTrackerOverlayStyle = 1;
p sure this is meant to be 0 by default

2022-11-28 11:57 UTC, Lulonaut approved these changes

2022-11-28 22:10 UTC, romangraef approved these changes

2022-11-28 22:10 UTC, merged