Gui element scale
NotEnoughUpdates/NotEnoughUpdates pull request #485
Opened 2022-12-09 13:09 UTC by NopoTheGamer

lunar client emote

2022-12-09 13:59 UTC, hannibal002 commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/TextOverlay.java
> +		if (!dummy) {
What's the dummy for?

2022-12-21 22:59 UTC, romangraef requested changes
Gui Editor shows all overlays in the top left corner with neu gui scale on auto and minecraft gui scale on normal, 1440p display resolution (the pet overlay renders in the far bottom right outside of the editor)
![image](https://user-images.githubusercontent.com/20768569/209018978-b006871f-c0c6-4557-97f5-1a709c6254b1.png)

![image](https://user-images.githubusercontent.com/20768569/209019148-38b1f36e-fffb-4630-856b-53202d1a61fa.png)

2022-12-22 03:09 UTC, romangraef approved these changes

2022-12-22 18:47 UTC, Lulonaut approved these changes

2022-12-23 16:48 UTC, hannibal002 approved these changes
Worked like a charm. Even with Minecraft Gui Scale!

2022-12-23 16:48 UTC, merged