Added some things
NotEnoughUpdates/NotEnoughUpdates pull request #49
Opened 2021-12-30 16:59 UTC by efefury

Added experiment timer todo overlay 
Added total xp if player is above cata 50 in /pv
Added daily powder/catacombs runs to todo overlay
Added a way to include kismet feather to profit calculator

2021-12-30 18:21 UTC, Lulonaut approved these changes
lgtm

2022-01-01 16:53 UTC, Lulonaut submitted a review, later dismissed
tested all the features
lgtm

2022-01-01 20:33 UTC, IRONM00N requested changes
:trollface:

2022-01-01 20:33 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
> +                if(totalXpStr != null){
needs a space after the if

2022-01-01 20:33 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
> +                }else {
needs a space before the else

2022-01-01 20:33 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
> +                String totalXpStr  = null;
only 1 space before the `=`

2022-01-01 20:33 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
> +                    totalXpStr = EnumChatFormatting.GRAY + "Total XP: " +EnumChatFormatting.DARK_PURPLE+ Utils.formatNumberWithDots((long) levelObj.totalXp);
unequal spacing on `+`

2022-01-01 20:51 UTC, IRONM00N approved these changes

2022-01-01 20:58 UTC, Lulonaut approved these changes
I am being forced to accept this

2022-01-01 21:56 UTC, NopoTheGamer approved these changes
looks good

2022-01-01 21:56 UTC, merged