Museum: Display hydrated items for items taken outside of the repo
NotEnoughUpdates/NotEnoughUpdates pull request #492
Opened 2022-12-12 20:09 UTC by romangraef

Follows #487

2022-12-17 01:00 UTC, NopoTheGamer commented
![image](https://user-images.githubusercontent.com/40329022/208214768-0e279290-cfe8-4e92-a775-799ce7cf54b3.png)
![image](https://user-images.githubusercontent.com/40329022/208214776-f1e8d9ea-5e89-4a34-8c15-a037ca508821.png)
kills fps :(

2022-12-21 12:13 UTC, Lulonaut submitted a review, later dismissed

2022-12-21 12:14 UTC, jani270 commented
me when not tested ingame

2022-12-21 12:15 UTC, Lulonaut commented
I don't have minecraft on windows 😭

2022-12-21 12:16 UTC, jani270 commented
> I don't have minecraft on windows 😭

😭

2022-12-22 03:59 UTC, NopoTheGamer approved these changes

2022-12-23 16:58 UTC, hannibal002 requested changes
Please disable the feature by default. Additionally, I don't like the highlighting at all. Maybe just add an extra line in the lore?

2022-12-23 17:04 UTC, hannibal002 commented
Furthermore, the config does not save after reloading. Can reproduce but can't find the error in code.

https://discord.com/channels/516977525906341928/1055881432465166476/1055881432465166476

2022-12-23 17:06 UTC, Lulonaut commented
> Furthermore, the config does not save after reloading. Can reproduce but can't find the error in code.
> 
> https://discord.com/channels/516977525906341928/1055881432465166476/1055881432465166476

the Expose annotation is missing at the config values

2022-12-23 19:01 UTC, romangraef commented
> Please disable the feature by default. Additionally, I don't like the highlighting at all. Maybe just add an extra line in the lore?
You can disable the highlighting already and there is already an extra line in the lore.

2022-12-24 01:21 UTC, NopoTheGamer approved these changes
I would prefer it if you didnt force push all of your changes

2022-12-24 01:22 UTC, romangraef commented
I would prefer to have clean commits. You can compare two force pushes using github by clicking [COMPARE] next to the force push message (or on your client use standard git diff commands)
![image](https://user-images.githubusercontent.com/20768569/209416696-a38c2ea6-1550-42e5-af53-f2ae747cafa4.png)

2022-12-24 01:25 UTC, NopoTheGamer commented
1. clean commits dont do anything? it doesn't effect the main repo 2. comparing isn't that helpful when you also merged master in the same push

2022-12-27 13:55 UTC, Lulonaut submitted a review, later dismissed

2022-12-27 14:15 UTC, NopoTheGamer requested changes
i was thiking especially with lulo adding something for museum, why don't we make a config section for museum stuff. misc is getting kinda full

2022-12-27 14:21 UTC, jani270 commented
Im fairly sure this is caused by other funny mods: https://i.imgur.com/T6o5toV.gif (Also the gif is like 15 fps so its alot faster ingame)
Just want to bring that up because im sure it will come up in support

2023-01-17 13:55 UTC, Lulonaut approved these changes

2023-01-17 20:13 UTC, romangraef reviewed
Just noticed that this does not properly displace the inventory buttons on the right side. Maybe we should add a InventoryButtonPositionEvent so that we dont put more shit into that weird if else in RenderListener

2023-01-25 18:32 UTC, hannibal002 commented
When will the PR remove the cheap museum overlay stuff? The current version here still contains bugs.

2023-02-03 07:47 UTC, NopoTheGamer requested changes

2023-02-03 07:47 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
> +	public Museum museum = new Museum();
I feel like this should be lower down

2023-02-03 07:47 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
> +		name = "Misc Overlays",
This change should be reverted

2023-02-03 17:09 UTC, jani270 commented on src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
> +	public Museum museum = new Museum();
Also "Musem overlays"

2023-02-10 12:09 UTC, NopoTheGamer approved these changes

2023-02-11 11:42 UTC, Lulonaut approved these changes

2023-02-17 20:25 UTC, romangraef commented
Discontinued in favor or #621

2023-02-17 20:25 UTC, closed without merging