Add sounds and rework the existing textures to custom Dwarven Mines /…
NotEnoughUpdates/NotEnoughUpdates pull request #51
Opened 2022-01-03 19:07 UTC by romangraef

2022-01-03 19:09 UTC, romangraef commented
That pr was meant to go into :dokm, but i think this also could go into :master

2022-01-04 01:19 UTC, NopoTheGamer requested changes

2022-01-04 01:19 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
> +            desc = "Allows texture packs to retexture blocks in the Crystal Hollows. If you don't have a texturepack that does this, you should leave this off"
```suggestion
            desc = "Allows texture packs to retexture blocks in the Crystal Hollows. If you don't have a texture pack that does this, you should leave this off"
```
you put a space between the other texture packs

2022-01-04 01:19 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/commands/Commands.java
> +    SimpleCommand dokmTest = new SimpleCommand("dokmTest", new SimpleCommand.ProcessCommandRunnable() {
move this to /neudevtest

2022-01-11 19:40 UTC, DoKM approved these changes

2022-01-13 01:05 UTC, NopoTheGamer commented
it seems to work fine but it would be nice if the audio didn't [stack](https://notenoughupdates.discord.com/channels/516977525906341928/832652653292027904/930989575944413275)

2022-01-13 13:51 UTC, NopoTheGamer approved these changes

2022-01-13 13:51 UTC, NopoTheGamer approved these changes

2022-01-13 16:42 UTC, Lulonaut approved these changes

2022-01-15 23:49 UTC, IRONM00N requested changes

2022-01-15 23:49 UTC, IRONM00N commented on src/main/resources/assets/notenoughupdates/sounds/titaniumbreak.json
> +{"debouncer":20}
```suggestion
{ "debouncer": 20 }
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/resources/assets/notenoughupdates/sounds/mithrilbreak.json
> +{"debouncer":20}
```suggestion
{ "debouncer": 20 }
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/resources/assets/notenoughupdates/sounds/gemstonetopazbreak.json
> +{"debouncer":20}
```suggestion
{ "debouncer": 20 }
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/resources/assets/notenoughupdates/sounds/gemstonesapphirebreak.json
> +{"debouncer":20}
```suggestion
{ "debouncer": 20 }
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/resources/assets/notenoughupdates/sounds/gemstonerubybreak.json
> +{"debouncer":20}
```suggestion
{ "debouncer": 20 }
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/resources/assets/notenoughupdates/sounds/gemstonejasperbreak.json
> +{"debouncer":20}
```suggestion
{ "debouncer": 20 }
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/resources/assets/notenoughupdates/sounds/gemstonejadebreak.json
> +{"debouncer":20}
```suggestion
{ "debouncer": 20 }
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/resources/assets/notenoughupdates/sounds/gemstoneamethystbreak.json
> +{"debouncer":20}
```suggestion
{ "debouncer": 20 }
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/resources/assets/notenoughupdates/sounds/gemstoneamberbreak.json
> +{"debouncer":20}
```suggestion
{ "debouncer": 20 }
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/commands/Commands.java
> +                } catch (Exception ignored) {
```suggestion
                } catch (Exception ignored) {}
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/commands/Commands.java
> +                }
```suggestion
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/commands/Commands.java
> +                } catch (Exception ignored) {
```suggestion
                } catch (Exception ignored) {}
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/commands/Commands.java
> +                }
```suggestion
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/commands/Commands.java
> +                } catch (Exception ignored) {
```suggestion
                } catch (Exception ignored) {}
```

2022-01-15 23:49 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/commands/Commands.java
> +                }
```suggestion
```

2022-01-15 23:51 UTC, romangraef commented
you serious?

2022-01-15 23:52 UTC, IRONM00N commented
> you serious?

:)

2022-01-15 23:52 UTC, jani270 commented
> you serious?

yes he is

2022-01-16 00:02 UTC, IRONM00N approved these changes

2022-01-16 00:03 UTC, merged