cheapest museum item to donate
NotEnoughUpdates/NotEnoughUpdates pull request #522
Opened 2022-12-26 14:16 UTC by Lulonaut

depends on #492

still needs better detection for armor (working on it) but works

2022-12-26 14:16 UTC, efefury commented
so true

2022-12-26 14:17 UTC, jani270 commented
working version btw

2022-12-26 15:04 UTC, hannibal002 commented
Though efe is working on this? Is this a Collab?

2022-12-26 15:04 UTC, NopoTheGamer commented
more than 1 person working on a pr :scream:

2022-12-26 22:40 UTC, efefury commented
multiple people working on a PR :scream_cat:

2022-12-27 13:56 UTC, Lulonaut commented
_should_ be ready now

2023-01-01 23:27 UTC, NopoTheGamer commented on src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/inventory/MuseumCheapestItemOverlay.kt
> +                println(name)
println(lunar)

2023-01-01 23:27 UTC, NopoTheGamer commented on src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/inventory/MuseumCheapestItemOverlay.kt
> +                println(name)
nvm i shouldnt probably look at old commits only

2023-01-03 20:48 UTC, jani270 submitted a review, later dismissed
Bugs: 
- After opening the museum for the first time the museum overlay is blank, this is fixed after opening the 3rd page
- The text "Visit all pages..." only appears on the 4th page 
^ Both of those bugs were tested in the Weapons menu
- Some Items show Unknown because they dont have a lowest bin. You might want to change that to cant find... 

Suggestion:
- Upon clicking a item we could show the recipe
- Use the texture from the minion helper (One of the buttons could be using raw craft cost instead of lb)
  Note: We could change the texture to not having the buttons on the texture directly, this requires a change in the minion overlay tho.
- Add a * to items that got a higher tier (like Tita drill x555 would show a * because there is an x655)
- Show the Overlay on the main page "Your Museum"

2023-01-19 22:32 UTC, jani270 reviewed
The tooltip acts pretty weird it dosent show on the ride side of your mouse
Minion Helper: https://i.imgur.com/4vnicZo.png
Museum: https://i.imgur.com/WYEKvrf.png

2023-01-19 22:37 UTC, jani270 commented
Crashed while hovering over an item with a unknown bin:
```
java.lang.ArrayIndexOutOfBoundsException: 5
	at io.github.moulberry.notenoughupdates.util.Utils.shortNumberFormat(Utils.java:348)
	at io.github.moulberry.notenoughupdates.util.Utils.shortNumberFormat(Utils.java:350)
	at io.github.moulberry.notenoughupdates.util.Utils.shortNumberFormat(Utils.java:350)
	at io.github.moulberry.notenoughupdates.util.Utils.shortNumberFormat(Utils.java:350)
	at io.github.moulberry.notenoughupdates.util.Utils.shortNumberFormat(Utils.java:350)
	at io.github.moulberry.notenoughupdates.util.Utils.shortNumberFormat(Utils.java:350)
	at io.github.moulberry.notenoughupdates.miscfeatures.inventory.MuseumCheapestItemOverlay.drawLines(MuseumCheapestItemOverlay.kt:212)
	at io.github.moulberry.notenoughupdates.miscfeatures.inventory.MuseumCheapestItemOverlay.onDrawBackground(MuseumCheapestItemOverlay.kt:101)

2023-02-14 17:24 UTC, Lulonaut commented
should be ready now :clueless:

2023-02-19 01:01 UTC, NopoTheGamer approved these changes

2023-02-24 15:09 UTC, hannibal002 requested changes

2023-02-24 15:09 UTC, hannibal002 commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/MiscOverlays.java
> +import io.github.moulberry.notenoughupdates.core.config.annotations.ConfigEditorColour;
why

2023-02-24 15:11 UTC, hannibal002 commented
![image](https://user-images.githubusercontent.com/24389977/221214357-a3479c06-f620-4237-b488-3b7317d2e4fe.png)

This is really hard to read. Maybe render with different shader options?

2023-02-24 15:14 UTC, hannibal002 commented
Why does this option in the config exist

![image](https://user-images.githubusercontent.com/24389977/221214641-a281d50f-8baa-49a0-acd2-1256025fb7d2.png)

When there is already this toggle button in the gui?

![image](https://user-images.githubusercontent.com/24389977/221214868-2cf29aca-af29-4fc1-9775-418e82c0c559.png)

2023-02-24 15:15 UTC, hannibal002 commented
Can we show this
![image](https://user-images.githubusercontent.com/24389977/221215137-365182a3-f5cf-4d66-a9ca-16d1260f2db4.png)

like in the hypixel ah inventory?
![image](https://user-images.githubusercontent.com/24389977/221215235-d1129863-a250-48e9-bad6-40598625dd5d.png)

2023-02-24 15:17 UTC, hannibal002 commented
Minion helper is using the yellow non-bold formatting for the last line.
![image](https://user-images.githubusercontent.com/24389977/221215435-7b3e006d-f802-4412-8d0b-e3c48c60dd41.png)

Same as Hypixel itself:

![image](https://user-images.githubusercontent.com/24389977/221215566-70d55667-db73-4b88-87eb-38c7f4843bcb.png)

Why are we inventing a new design there?

![image](https://user-images.githubusercontent.com/24389977/221215622-3ad636ea-7819-4599-9f1a-1cfb6a942c0f.png)

2023-02-24 15:19 UTC, hannibal002 commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/MiscOverlays.java
> +import io.github.moulberry.notenoughupdates.core.config.annotations.ConfigEditorColour;
I have fixed it already.

2023-03-02 16:12 UTC, romangraef approved these changes

2023-03-06 14:30 UTC, romangraef approved these changes

2023-03-11 14:59 UTC, hannibal002 approved these changes
:(

2023-03-11 23:53 UTC, NopoTheGamer approved these changes

2023-03-11 23:54 UTC, merged