Made it so barriers appear where you are unable to slot bind to
NotEnoughUpdates/NotEnoughUpdates pull request #528
Opened 2022-12-28 14:52 UTC by NopoTheGamer

![image](https://cdn.discordapp.com/attachments/832652653292027904/1057672449493319773/image.png)

2022-12-30 19:35 UTC, hannibal002 approved these changes
Does exactly what I think you want us to think this feature has to be about. I'm pleased to learn this feature exist, thanks for your PR!

2022-12-31 02:31 UTC, romangraef approved these changes

2022-12-31 15:40 UTC, jani270 commented
It would be cool if the slot you bind from still shows as the real item. 

![image](https://user-images.githubusercontent.com/69345714/210147491-50a75277-bf13-4e39-b5b7-b6447d3e930e.png)

2023-01-01 18:27 UTC, hannibal002 approved these changes

2023-01-01 18:38 UTC, Lulonaut approved these changes

2023-01-01 19:01 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/events/ReplaceItemEventInventory.java
> +public class ReplaceItemEventInventory extends NEUEvent {
bruh i forgot to delete that event thats useless now

2023-01-03 12:52 UTC, Lulonaut submitted a review, later dismissed

2023-01-03 12:52 UTC, Lulonaut commented
/home/runner/work/_temp/66d03d91-e68f-4d74-aff5-2142eb9dbe54.sh: line 3: infer: command not found

2023-01-11 18:24 UTC, hannibal002 approved these changes

2023-01-11 20:59 UTC, romangraef requested changes
![image](https://user-images.githubusercontent.com/20768569/211916590-11056fe7-ae53-423d-b0c1-d75503e19c7e.png)
this is still broken (binding with armor)

2023-01-14 01:27 UTC, romangraef approved these changes

2023-01-17 13:59 UTC, Lulonaut approved these changes

2023-01-18 17:01 UTC, hannibal002 approved these changes

2023-01-18 17:01 UTC, merged