Bingo has already enough to do.
NotEnoughUpdates/NotEnoughUpdates pull request #583
Opened 2023-02-02 20:19 UTC by hannibal002

Removed stuff from the todo overlay that is unrealistic to do on a bingo profile.
Uses a toggle that is default off.

2023-02-02 20:37 UTC, jani270 commented
i dont like that cakes being removed, they are a quite cool mini bonus

2023-02-03 07:58 UTC, NopoTheGamer requested changes

2023-02-03 07:58 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/MiscOverlays.java
> +		desc = "Hide some tasks from the todo overlay while on a bingo profile: Cookie Buff, Godpot, Heavy Pearls, Cakes, Crimson Isle Quests"
You added back cakes

2023-02-05 02:17 UTC, NopoTheGamer submitted a review, later dismissed

2023-02-05 22:32 UTC, romangraef approved these changes

2023-02-05 22:38 UTC, NopoTheGamer approved these changes

2023-02-11 11:37 UTC, Lulonaut approved these changes

2023-02-11 11:37 UTC, merged