Custom items in /neucustomize
NotEnoughUpdates/NotEnoughUpdates pull request #609
Opened 2023-02-12 06:06 UTC by NopoTheGamer

![image](https://user-images.githubusercontent.com/40329022/218295699-cf433294-54d3-4118-816c-ff6a2f2ca1fc.png)
![image](https://user-images.githubusercontent.com/40329022/218295706-3ad2aa34-6470-46fc-8d3a-1761c1ea7304.png)
![image](https://user-images.githubusercontent.com/40329022/218295742-3a9df381-2cdd-4aa8-a0a3-ff28c7811220.png)

2023-02-21 22:58 UTC, romangraef requested changes
I feel like there is a pretty large amount of code duplication and overlapping concepts in this PR. There are about a dozen mixins all with the same code (or code that could be hooked out to the same function and be a single line in the actual mixin).

2023-02-21 22:58 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinLayerArmorBase.java
> +		return newStack;
I don't like having "complex" code in mixins, since crashes in mixins are that much harder to trace back.

2023-02-22 17:48 UTC, romangraef approved these changes

2023-02-24 15:04 UTC, hannibal002 submitted a review, later dismissed
My potato hoe is now a potato.

2023-02-24 21:23 UTC, Lulonaut approved these changes

2023-03-08 16:32 UTC, romangraef approved these changes

2023-03-11 14:40 UTC, hannibal002 approved these changes

2023-03-11 15:05 UTC, Lulonaut approved these changes

2023-03-11 15:05 UTC, merged