Multiple tweaks to the Todo Overlay
NotEnoughUpdates/NotEnoughUpdates pull request #624
Opened 2023-02-22 23:32 UTC by Plantterror

- Fix experiments resetting at midnight, when it should be at catacombs.
- Remove checking Cookie buff from player list, instead delegating that to opening the Skyblock Menu for a more accurate timer. I cannot do this with the God Potion due to false positives.
- Daily NPC Buy Limit, resets at catacombs. When you buy 640 (6400 during Diaz) of an item, this will activate the timer for the next day. Right now this is based off of the chat message, I theorize it would take too many resources looping through all NPC shop names and shop items to check for the lore tag that is added, but it means that you can sometimes not activate the timer.

Let me know if there's anything I could do better about this code or if you want me to add some other potential features while I'm at it.

2023-02-23 04:02 UTC, Plantterror commented
Some more things i might do:
- Beacon Powering (suggested by Obsidian#5955)
- Cake timer updates while you attempt to eat a cake already consumed prior
- Daily dungeon runs? that code might be all over the place

2023-03-02 16:37 UTC, romangraef approved these changes

2023-03-02 17:55 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
> +			switch (containerName){
```suggestion
			switch (containerName.intern()) {
```

2023-03-02 17:56 UTC, romangraef requested changes
Also format

2023-03-02 17:59 UTC, Plantterror commented
> Also format

Can you be more specific on this?

2023-03-02 18:07 UTC, romangraef approved these changes

2023-03-02 18:13 UTC, Plantterror commented
I noticed a bug where the Election part of the player listing can actually trigger a crimson isle quest to be "completed" even though it shouldn't be. I'm going to work on that.

2023-03-03 16:37 UTC, Plantterror commented
@jani270 This is both a bug fix and a feature drop, can you change the labels accordingly

2023-03-07 13:51 UTC, romangraef submitted a review, later dismissed

2023-03-09 20:32 UTC, romangraef approved these changes

2023-03-11 14:03 UTC, hannibal002 approved these changes

2023-03-11 14:55 UTC, Lulonaut approved these changes

2023-03-11 14:55 UTC, merged