Fix crafting overlay
NotEnoughUpdates/NotEnoughUpdates pull request #64
Opened 2022-01-13 23:26 UTC by romangraef

2022-01-15 01:37 UTC, NopoTheGamer submitted a review, later dismissed
works

2022-01-15 20:06 UTC, Lulonaut approved these changes

2022-01-15 23:36 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
> +        } catch (Exception ignored) {
aaaaaaaaaaaaaa

2022-01-15 23:37 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
> +            } catch (Exception ignored) {
more aaaaaaaaa

2022-01-15 23:38 UTC, IRONM00N requested changes
please fix the empty catch closing brace being on a new line

2022-01-15 23:44 UTC, jani270 commented
PepeLaugh

2022-01-15 23:52 UTC, IRONM00N requested changes
:trollface:

2022-01-15 23:52 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
> +        } catch (IOException ignored) {
```suggestion
        } catch (IOException ignored) {}
```

2022-01-15 23:52 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
> +        }
```suggestion
```

2022-01-15 23:52 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
> +                } catch (NBTException ignored) {
```suggestion
                } catch (NBTException ignored) {}
```

2022-01-15 23:52 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
> +                }
```suggestion
```

2022-01-15 23:52 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
> +            } catch (Exception ignored) {
```suggestion
            } catch (Exception ignored) {}
```

2022-01-15 23:52 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
> +            }
```suggestion
```

2022-01-15 23:52 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
> +            } catch (IllegalAccessException ignored) {
```suggestion
            } catch (IllegalAccessException ignored) {}
```

2022-01-15 23:52 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
> +            }
```suggestion
```

2022-01-16 00:01 UTC, IRONM00N requested changes

2022-01-16 00:01 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
> +                        }
```suggestion
                        } catch (IOException ignored) {}
```

2022-01-16 00:01 UTC, IRONM00N approved these changes

2022-01-16 00:02 UTC, merged