Make ApiUtil accept gzip encoding
NotEnoughUpdates/NotEnoughUpdates pull request #677
Opened 2023-04-04 14:16 UTC by DeDiamondPro

Tell the server we support gzip encoding, so they can send gzipped data instead of raw data.
Can speed up things like fetching bazaar prices and pv on slow connections since hypixel will send gzipped data if we say we accept it.

2023-04-04 17:02 UTC, romangraef requested changes
I was originally planning to do this, but did not because moulberry did not support this (and that was the only one who i really cared about at that time) (to be clear: moulberrys apis do support Accept-Encoding: gzip and respond accordingly, but that does not get properly cached, so we kept the .gz urls). But i guess for the bazaar data it does make sense as well. However i would not set the request property when we already plan to gunzip (since we would need to double gunzip, and that does not improve compression)

2023-04-04 17:17 UTC, DeDiamondPro commented
> I was originally planning to do this, but did not because moulberry did not support this (and that was the only one who i really cared about at that time) (to be clear: moulberrys apis do support Accept-Encoding: gzip and respond accordingly, but that does not get properly cached, so we kept the .gz urls). But i guess for the bazaar data it does make sense as well. However i would not set the request property when we already plan to gunzip (since we would need to double gunzip, and that does not improve compression)

This is actually a non-issue since when you request a .gz file the encoding returns null, so no encoding, meaning no double compression

2023-04-04 17:32 UTC, DeDiamondPro commented
Here are the logs from a quick test a ran to see what used gzip encoding and what didn't:
```
https://moulberry.codes/permscapes.json gzip
https://moulberry.codes/activecapes.json gzip
https://api.hypixel.net/resources/skyblock/election?key= gzip
https://moulberry.codes/auction_averages_lbin/1day.json.gz? null
https://api.hypixel.net/skyblock/bazaar? gzip
https://moulberry.codes/auction_averages/3day.json.gz? null
https://moulberry.codes/lowestbin.json.gz? null
https://api.mojang.com/users/profiles/minecraft/dediamondpro? null
https://api.hypixel.net/player?key=&name=dediamondpro gzip
https://api.hypixel.net/guild?key=&player=0b4d470ff2fb487493341eaef8ba4804 gzip
https://api.hypixel.net/skyblock/profiles?key=&uuid=0b4d470ff2fb487493341eaef8ba4804 gzip
https://api.hypixel.net/status?key=&uuid=0b4d470ff2fb487493341eaef8ba4804 gzip
```
As you can see everything that is already gzipped doesn't get gzipped again

2023-04-04 17:42 UTC, romangraef commented
> This is actually a non-issue since when you request a .gz file the encoding returns null, so no encoding, meaning no double compression

That is an implementation detail of moulberrys server, not an actual requirement of any standard whatsoever.

2023-04-04 17:59 UTC, romangraef approved these changes

2023-04-11 17:26 UTC, Lulonaut approved these changes

2023-04-22 11:37 UTC, NopoTheGamer approved these changes

2023-04-22 11:37 UTC, merged