Show maxed HOTM perks and clean up code
NotEnoughUpdates/NotEnoughUpdates pull request #69
Opened 2022-01-23 05:08 UTC by FluxCapacitor2

In this PR, I removed a lot of repeated code and replaced it with a nice utility method, `renderHotmPerk`. Sorry for the absolutely massive diff, but I think it's worth it. It should work exactly the same as before if I did everything right.

Also, I added the max level of each perk as a parameter to the `renderHotmPerk` method, which will now render a diamond instead of an emerald for perks that are unlocked and maxed.

Also, before I reworked it, the `List<String>` that represented the item's tooltip was set to `null` after the hovering text was drawn on the screen, probably for GC reasons. I'm not sure if this is necessary now because everything is contained within a method, so once the context is left, all the variables in the method's scope should be discarded.

Currently, the code to draw one perk looks like this:
```java
boolean crystallizedunlocked = (crystallized > 0);
            List<String> crystallizedTooltip = null;
            GlStateManager.color(1, 1, 1, 1);
            GlStateManager.disableLighting();
            Minecraft.getMinecraft().getRenderItem().renderItemIntoGUI(new ItemStack((crystallizedunlocked ? Items.emerald : Items.coal)), (int) (guiLeft + xStart + 303), (int) (guiTop + yStartTop + 90));
            GlStateManager.enableLighting();
            if (mouseX >= guiLeft + xStart + 303 && mouseX < guiLeft + xStart + 319) {
                if (mouseY >= guiTop + yStartTop + 90 && mouseY <= guiTop + yStartTop + 106) {
                    crystallizedTooltip = Lists.newArrayList(
                            (crystallizedunlocked ? EnumChatFormatting.GREEN : EnumChatFormatting.RED) + "Crystallized",
                            "§7Level " + crystallized + EnumChatFormatting.DARK_GRAY + "/30",
                            "",
                            "§7Grants §a+§a" + crystallizedStat + "§7 §6⸕ Mining",
                            "§6Speed §7and a §a" + crystallizedStat + "%§7 §7chance",
                            "§7to deal §a+1 §7extra damage near",
                            "§7§5Fallen Stars§7."
                    );
                    Utils.drawHoveringText(crystallizedTooltip, mouseX, mouseY, width, height, -1, fr);
                    crystallizedTooltip = null;
                }
            }
```
which is now replaced by:
```java
renderHotmPerk(
    crystallized, // an int representing the level of the perk
    (int) (guiLeft + xStart + 303), (int) (guiTop + yStartTop + 90), // x and y position to render the item
    mouseX, mouseY,
    () -> Lists.newArrayList( 
          "Crystallized",
          "§7Level " + crystallized + EnumChatFormatting.DARK_GRAY + "/30",
          "",
          "§7Grants §a+§a" + crystallizedStat + "§7 §6⸕ Mining",
          "§6Speed §7and a §a" + crystallizedStat + "%§7 §7chance",
          "§7to deal §a+1 §7extra damage near",
          "§7§5Fallen Stars§7."
    ), // tooltip text (placed in a supplier so that we only compute it when it's needed)
    30 // max perk level
);
```
Also the Great Explorer perk was off by 1 pixel, so I adjusted it to line up with the other perks in the same horizontal position on the tree.

If you have any suggestions or edits you want to make, please let me know and I'll implement them. I'm also willing to work on new features or bugs, I just don't know where to start.

2022-01-23 05:25 UTC, NopoTheGamer approved these changes
Looks good

2022-01-23 22:22 UTC, Lulonaut approved these changes

2022-01-23 22:29 UTC, IRONM00N commented
> absolutely massive diff
its not even over 10k I think its fine

2022-01-23 22:32 UTC, IRONM00N requested changes
Ty for commenting your code

2022-01-23 22:32 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
> +    // Render a standard HOTM perk that can be levelled.
make this a Javadoc comment instead

2022-01-23 22:32 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
> +    // Render a pickaxe ability that can be unlocked once and not levelled.
ditto

2022-01-23 22:32 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
> +    // A separate method similar to the one above, but allowing the caller to specify an ItemStack to render. Used for rendering Peak of the Mountain and perks that are unlocked once and not upgraded
ditto

2022-01-24 00:01 UTC, FluxCapacitor2 commented
Done. I can document the parameter names if you want me to.

2022-01-24 21:05 UTC, Lulonaut approved these changes

2022-01-24 21:07 UTC, IRONM00N approved these changes
Thank you for your contribution.

2022-01-27 10:20 UTC, NopoTheGamer approved these changes

2022-01-27 10:21 UTC, merged