PV Overhaul
NotEnoughUpdates/NotEnoughUpdates pull request #708
Opened 2023-05-27 20:58 UTC by kr45732

3-5 business days

2023-05-31 13:10 UTC, kr45732 commented
PV works
uhm merge conflicts pain

2023-05-31 13:45 UTC, kr45732 commented
one more thing for the future is to move all the profile specific stuff that are cached in individual pages into the SkyblockProfiles class

2023-06-01 13:25 UTC, ThatGravyBoat requested changes

2023-06-01 18:28 UTC, kr45732 commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/CrimsonIslePage.java
> +				new ArrayList<>(apiDojoTestNames.values()).get(i) + ": ",
Honestly not sure what's going on with the old code, refactored it.

2023-06-02 03:10 UTC, kr45732 commented
Ok tested PV, should be free of crashes/bugs now. Probably no further changes to this PR now.

2023-06-02 12:52 UTC, hannibal002 commented
`// This is to make infer happy but shouldn't be possible`
You can remove these comments.
I'm pretty sure `getSelectedProfile()` returns null immediately after a profile/world change.

2023-06-02 14:33 UTC, kr45732 commented
> `// This is to make infer happy but shouldn't be possible` You can remove these comments. I'm pretty sure `getSelectedProfile()` returns null immediately after a profile/world change.

This was since drawing all tasks are all called by the LevelPage which does the null check before drawing the tasks. But I can remove it.

2023-06-07 23:47 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/SkyblockProfiles.java
> +	private static final String defaultNbtData = "Hz8IAAAAAAAAAD9iYD9kYD9kAAMAPwI/Gw0AAAA=";
This still isnt valid GZIPped or non GZIPped NBT data, btw.

2023-06-07 23:48 UTC, romangraef approved these changes

2023-06-08 14:00 UTC, merged