Made Etherwarp overlay work with Etherwarp Conduit
NotEnoughUpdates/NotEnoughUpdates pull request #717
Opened 2023-06-09 21:59 UTC by Xupie

2023-06-12 14:54 UTC, romangraef approved these changes

2023-06-13 15:53 UTC, Lulonaut approved these changes

2023-06-27 08:46 UTC, NopoTheGamer requested changes
i am 98% sure this change does nothing

2023-06-27 11:25 UTC, NopoTheGamer commented
PR does nothing, the etherwarp conduit works without this pr

2023-06-27 11:25 UTC, closed without merging