Change kismet in dungeon profits to bazaar
NotEnoughUpdates/NotEnoughUpdates pull request #737
Opened 2023-06-25 16:27 UTC by heyngra

![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates/assets/25665974/a51fbb85-74f7-46a8-99ad-c9556f0c5f12)

2023-06-25 16:47 UTC, efefury commented
damn somebody uses this feature

2023-06-25 16:49 UTC, heyngra commented
i had it enabled and -1 irritated me asf

2023-06-25 16:50 UTC, efefury commented
> i had it enabled and -1 irritated me asf

i made the feature and i don't even use it myself

2023-06-26 14:43 UTC, romangraef requested changes

2023-06-26 14:43 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
> +					double kismetPrice = neu.manager.auctionManager.getBazaarInfo("KISMET_FEATHER").get("curr_buy").getAsFloat();
`getBazaarInfo` returns `null` if the bazaar api could not be queried.

2023-06-26 15:41 UTC, romangraef approved these changes

2023-06-27 08:31 UTC, NopoTheGamer approved these changes

2023-06-27 08:32 UTC, merged