Storage Overlay use /backpack
NotEnoughUpdates/NotEnoughUpdates pull request #740
Opened 2023-06-27 01:50 UTC by IRONM00N

idk if I did this correctly

2023-06-27 03:27 UTC, romangraef reviewed
Does this break the normal clicking on chests in the gui? will test tomorrow

2023-06-27 04:04 UTC, CalMWolfs commented
works fine for me, you can also remove the following file:
src/main/kotlin/io/github/moulberry/notenoughupdates/commands/help/StorageViewerWhyCommand.kt

2023-06-27 08:25 UTC, NopoTheGamer submitted a review, later dismissed

2023-06-27 14:26 UTC, romangraef requested changes

2023-06-27 14:26 UTC, romangraef commented on src/main/kotlin/io/github/moulberry/notenoughupdates/commands/dev/SimpleDevCommands.kt
> +                NotEnoughUpdates.INSTANCE.config.storageGUI.enableStorageGUI3 = false
This disables the storage when typing `/neuenableStorage`

2023-06-27 15:50 UTC, IRONM00N commented on src/main/kotlin/io/github/moulberry/notenoughupdates/commands/dev/SimpleDevCommands.kt
>              }.withHelp("Disable the neu storage overlay")
Should this not be "Enable the neu storage overlay"?

2023-06-27 20:22 UTC, jani270 commented
You might wanna add a very small cooldown between switching pages/after switching a few pages so this doesnt happen: "A kick occurred in your connection, so you were put in the SkyBlock lobby!"

2023-06-27 23:25 UTC, CalMWolfs commented
> You might wanna add a very small cooldown between switching pages/after switching a few pages so this doesnt happen: "A kick occurred in your connection, so you were put in the SkyBlock lobby!"

you can add these modified lines back in for this where they were before
public long storageOpenSwitchMillis = 0;
if (System.currentTimeMillis() - storageOpenSwitchMillis < 100) return;

2023-06-30 14:20 UTC, romangraef approved these changes

2023-07-05 23:58 UTC, NopoTheGamer approved these changes

2023-07-05 23:58 UTC, merged