Museum page
NotEnoughUpdates/NotEnoughUpdates pull request #773
Opened 2023-07-15 11:22 UTC by CalMWolfs

Requires
https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/pull/957

- Summary of total museum value along with the number of items donated from each category.
- You can click on a particular item to see when it was donated and if it is currently in the user's museum
![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates/assets/94038482/cc73c5fa-0393-41a5-9cf6-11f9b69287a3)

2023-07-16 14:33 UTC, Lulonaut submitted a review, later dismissed

2023-07-16 14:33 UTC, Lulonaut commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/SkyblockProfiles.java
> +					museumValue = -2;
I think its more helpful to show the repo notification here `Utils.showOutdatedRepoNotification()`

2023-07-16 20:48 UTC, jani270 requested changes
![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates/assets/69345714/0948ba8b-228e-4b5c-825d-4fce55c8bf06)
![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates/assets/69345714/5b46a5ab-9735-43fc-98d5-bf79dec631bf)
😡

2023-07-17 10:17 UTC, NopoTheGamer commented
It would be nice to have some sort of button that hides items you haven't submitted and only shows ones you have. Other than that LGTM

2023-07-18 10:18 UTC, CalMWolfs commented
> It would be nice to have some sort of button that hides items you haven't submitted and only shows ones you have. Other than that LGTM

Is it all good if this gets done in a future pr if there is need for it as I'm pretty busy for the next few weeks

2023-07-18 10:25 UTC, NopoTheGamer commented
> Is it all good if this gets done in a future pr if there is need for it as I'm pretty busy for the next few weeks
sure

2023-07-18 10:26 UTC, Lulonaut approved these changes

2023-07-18 10:27 UTC, NopoTheGamer approved these changes
unlucky efe

2023-07-18 10:27 UTC, merged