Fix bestiary page in PV
NotEnoughUpdates/NotEnoughUpdates pull request #805
Opened 2023-08-17 22:35 UTC by Lulonaut

Depends on [jani270/NotEnoughUpdates-REPO/2190bestiary](https://github.com/jani270/NotEnoughUpdates-REPO/tree/2190bestiary)

Aside from the total bestiary level, everything works.

2023-08-19 20:51 UTC, romangraef approved these changes

2023-08-27 09:17 UTC, jani270 requested changes
crashed while clicking on the levels page without having bestiary json
```
java.lang.NullPointerException: Rendering screen
	at io.github.moulberry.notenoughupdates.profileviewer.bestiary.BestiaryData.parseBestiaryData(BestiaryData.kt:107)
	at io.github.moulberry.notenoughupdates.profileviewer.SkyblockProfiles$SkyblockProfile.getBestiaryLevel(SkyblockProfiles.java:946)
	at io.github.moulberry.notenoughupdates.profileviewer.level.task.SlayingTaskLevel.drawTask(SlayingTaskLevel.java:165)
	at io.github.moulberry.notenoughupdates.profileviewer.level.LevelPage.lambda$drawPage$0(LevelPage.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at io.github.moulberry.notenoughupdates.profileviewer.level.LevelPage.drawPage(LevelPage.java:95)
	at io.github.moulberry.notenoughupdates.profileviewer.BasicPage.drawPage(BasicPage.java:142)
	at io.github.moulberry.notenoughupdates.profileviewer.GuiProfileViewer.drawScreen(GuiProfileViewer.java:417)
```

2023-08-27 15:51 UTC, romangraef approved these changes

2023-08-30 11:17 UTC, NopoTheGamer approved these changes
didnt crash (positive)

2023-08-30 11:17 UTC, merged