Re-add join command
NotEnoughUpdates/NotEnoughUpdates pull request #821
Opened 2023-09-02 21:26 UTC by romangraef

2023-09-04 16:44 UTC, Lulonaut submitted a review, later dismissed

2023-09-23 19:21 UTC, jani270 requested changes

2023-09-23 19:21 UTC, jani270 commented on src/main/kotlin/io/github/moulberry/notenoughupdates/commands/misc/JoinCommand.kt
> +    val kuudraLevelNames = listOf("BASIC", "HOT", "BURNING", "FIERY", "INFERNAL")
```suggestion
    val kuudraLevelNames = listOf("NORMAL", "HOT", "BURNING", "FIERY", "INFERNAL")
```

2023-09-26 17:11 UTC, Lulonaut approved these changes

2023-09-27 11:28 UTC, NopoTheGamer approved these changes

2023-09-27 11:28 UTC, merged