Default Armor Colour Feature
NotEnoughUpdates/NotEnoughUpdates pull request #825
Opened 2023-09-07 15:58 UTC by VixidDev

When enabled, renders all armor in their default colour. A couple people said they wanted this feature so I added it.

2023-09-08 14:19 UTC, romangraef requested changes

2023-09-08 14:19 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DefaultArmorColour.java
> +		}
This does not seem to be the correct way to parse an NBT tag. Please also consider adding a cache for this.

2023-09-09 17:27 UTC, romangraef requested changes

2023-09-09 17:27 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DefaultArmorColour.java
> +	private static Map<String, Integer> armorCache = new HashMap<>();
Consider using a `Map<String, Integer> armorColorCache = new IdentityHashMap<>();` instead, so you can cache the item resolution query step as well.

2023-09-09 17:27 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DefaultArmorColour.java
> +					exception.printStackTrace();
Please also cache failures. Otherwise this exception will repeatedly spam logs.

2023-09-09 17:27 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DefaultArmorColour.java
> +					exception.printStackTrace();
(Which is also enormously detrimental for performance, btw)

2023-09-09 19:21 UTC, romangraef commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DefaultArmorColour.java
> +				if (!erroredItems.contains(itemJson.get("internalname").getAsString())) {
Can you skip this entire calculation for errored items? The slow part is the exception itself (Exception#fillStackTrace), not the printing of it.

2023-09-20 21:00 UTC, romangraef approved these changes

2023-09-27 11:18 UTC, NopoTheGamer requested changes
![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates/assets/40329022/7a9c7ac7-9aae-4d73-81b6-ceb17f1f0ed4)
it just doesnt work?

2023-09-27 12:23 UTC, romangraef commented
@NopoTheGamer I'm pretty sure it is supposed to only change the model. The item can still be colored to make it properly identifiable, but on armor models of other players its less confusing that way.

2023-09-27 12:24 UTC, NopoTheGamer approved these changes
oh

2023-09-27 12:24 UTC, merged