Fix skyblock level calculations in PV
NotEnoughUpdates/NotEnoughUpdates pull request #828
Opened 2023-09-12 18:17 UTC by Lulonaut

Requires this repo branch: jani270:bestiaryprogress
see: https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/pull/982

This fixes some bugs with the skyblock level xp calculation caused by Hypixel API updates

Also overhauls the skyblock xp level calculation for the bestiary, which was broken by the bestiary API overhaul

2023-09-20 21:20 UTC, romangraef submitted a review, later dismissed

2023-09-20 22:19 UTC, jani270 requested changes
crash when you dont have repo (yes i know backup repo exists.)
```
java.lang.NullPointerException: Rendering screen
	at io.github.moulberry.notenoughupdates.profileviewer.bestiary.BestiaryData.calculateBestiarySkyblockXp(BestiaryData.kt:72)
	at io.github.moulberry.notenoughupdates.profileviewer.SkyblockProfiles$SkyblockProfile.getBestiaryXp(SkyblockProfiles.java:959)
```

2023-09-22 14:05 UTC, romangraef approved these changes

2023-09-27 11:09 UTC, NopoTheGamer approved these changes

2023-09-27 11:10 UTC, merged