Also check for sk1ers scrollable tooltips for recipe scrolling
NotEnoughUpdates/NotEnoughUpdates pull request #851
Opened 2023-10-03 02:02 UTC by NopoTheGamer

2023-10-03 12:40 UTC, romangraef requested changes
At that point I would argue in favour of just blocking scrolling entirely if any tooltip was rendered. Wouldn't change much, and we also add support for other tooltip scrolling mods, such as dulkir (and presumably also lunar). Open to debate on this, but I don't think it would take away much usability, while being way more compatible.

2023-10-03 12:41 UTC, NopoTheGamer commented
> At that point I would argue in favour of just blocking scrolling entirely if any tooltip was rendered. Wouldn't change much, and we also add support for other tooltip scrolling mods, such as dulkir (and presumably also lunar).

well i suggested that twice and just got ignored...

2023-10-04 10:03 UTC, Lulonaut approved these changes

2023-10-04 11:59 UTC, romangraef approved these changes

2023-10-04 12:31 UTC, merged