Fix enchanted books not working with bz keybind
NotEnoughUpdates/NotEnoughUpdates pull request #886
Opened 2023-10-18 15:19 UTC by Lulonaut

closes #885

Extracts the book name from the lore of the item.
Then searches directly with /bz since enchanted books can't be in the auction house

2023-10-19 21:31 UTC, nea89o requested changes

2023-10-19 21:31 UTC, nea89o commented on src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
> +							if (item.get("itemid").getAsString().equals("minecraft:enchanted_book")) {
Checking just for itemid will break for items that render as an enchanted book, but are *not* an enchanted book. For example the experience artifact.

2023-10-20 15:06 UTC, nea89o approved these changes

2023-10-20 20:34 UTC, DeDiamondPro approved these changes

2023-10-20 20:35 UTC, merged