Wishing Compass Solver, Metal Detector Solver improvements, add /neudiag, other misc changes
NotEnoughUpdates/NotEnoughUpdates pull request #90
Opened 2022-03-05 21:15 UTC by Keebler408

- Added Wishing Compass Solver that shows target coordinates using two samples. The text can be clicked to add a Skytils waypoint if Skytils is present.

- Lots of metal detector logic improvements, including solving using known locations based on Keeper coordinates. This usually only requires a single position. This also addresses cases where a solution cannot be found when Mines of Divan generation is glitched or people intentionally add/remove blocks around chests.

- Crystal Hollows crystal states are now updated when the Heart of the Mountain menu is opened.

- Added /neudiag command and `NEUDebugLogger` to support dynamic enabling/disabling of debug logging and dumping of diagnostic data for support/debugging purposes. Metal detector and wishing compass currently are supported, with the metal detector data being sufficient to investigate sporadic failures to find a solution.

- Added a Line utility class to support the Wishing Compass Solver.

- Various small `MiningOverlay` fixes, tweaks, and clarified naming.

- Minor name tweaks for increased clarity.

- Renamed CraftyOldMiner to Keebler408

2022-03-05 22:01 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
> +import io.github.moulberry.notenoughupdates.miscfeatures.*;
me no like

2022-03-05 22:07 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
> +}
why is every line changed?

2022-03-05 22:08 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
> +                            replaceForgeOrAdd(item, profileConfig.forgeItems, true);
fix formatting, please

2022-03-05 22:08 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
> +                            replaceForgeOrAdd(item, profileConfig.forgeItems, true);
ditto

2022-03-05 22:08 UTC, IRONM00N commented on src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
> +						if(profileConfig != null) {
```suggestion
						if (profileConfig != null) {
```

2022-03-05 22:09 UTC, IRONM00N requested changes
see comments I made

2022-03-05 22:50 UTC, Keebler408 commented
@IRONM00N 
> see comments I made
Addressed. What are your thoughts on adding a .gitattributes and .idea/codeStyles/Project.xml to the project to prevent some of these issues in the future?

2022-03-06 01:18 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/CrystalWishingCompassSolver.java
> +			.contains("skytils"));
cant you do `Loader.isModLoaded("skytils")` ?

2022-03-06 01:50 UTC, NopoTheGamer approved these changes

2022-03-06 16:17 UTC, Lulonaut approved these changes

2022-03-08 03:43 UTC, IRONM00N commented
> @IRONM00N 
> 
> Comments have been addressed.
> 
> 
> 
> What are your thoughts on adding a .gitattributes to the project to prevent the line ending issues that were seen on Mining.java in the future? Adding .gitattributes would, of course, be in a separate PR. See https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/ for details if you need them.

I would appreciate it, I didn't realize that we never added a .gitattributes yet.

2022-03-08 03:43 UTC, IRONM00N approved these changes

2022-03-08 03:44 UTC, merged