Add NBT Data to Profile Viewer Tabs and XP Bars
NotEnoughUpdates/NotEnoughUpdates pull request #94
Opened 2022-03-16 19:09 UTC by walkerselby

Add NBT Data Support for Resources in Tabs
Add NBT Data Support for Resources in XP Bars
Optimize renderTabs function
Optimize mouseClicked Function
Optimize ProfileViewerPage Enum

2022-03-17 09:54 UTC, NopoTheGamer commented on src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
> +		for (int index = 0; pages.size()>index; index++){
```suggestion
		for (int index = 0; pages.size() > index; index++){
```
:slightly_smiling_face:

2022-03-17 20:28 UTC, romangraef requested changes
This PR looks fine in general, but there are a LOT of problems with formatting, please see our .editorconfig or our .idea/codeStyles. There will also be a lot of conflicts with the [pvbingo](https://github.com/NotEnoughUpdates/NotEnoughUpdates/tree/pvbingo/) branch, so theres a good chance lulo or nopo will ask you to rebase on that.

2022-03-17 22:06 UTC, walkerselby commented
> This PR looks fine in general, but there are a LOT of problems with formatting, please see our .editorconfig or our .idea/codeStyles. There will also be a lot of conflicts with the [pvbingo](https://github.com/NotEnoughUpdates/NotEnoughUpdates/tree/pvbingo/) branch, so theres a good chance lulo or nopo will ask you to rebase on that.

Rebased and edited the formatting. git was being git, so I think it went correctly, but we shall see. Thank you for the review, and apologies for the formatting issues.

2022-03-24 07:02 UTC, NopoTheGamer approved these changes

2022-03-26 18:28 UTC, walkerselby reviewed
Should all be addressed and current with the master branch now.

2022-03-26 18:43 UTC, Lulonaut approved these changes

2022-03-27 05:59 UTC, NopoTheGamer approved these changes

2022-03-27 17:09 UTC, romangraef approved these changes
this is one fucked up git history, but at least the code is good :+1: maybe githubs squash + merge can make this work without looking to weird in git logs, im not sure what git operations they actually do with squash + merge

2022-03-27 17:13 UTC, IRONM00N approved these changes

2022-03-27 17:13 UTC, merged